### ISSUE TITLE
Spaces are not allowed in autolinks

### ISSUE THREAD

**Issue by lostenderman** [lostenderman/markdown#10]
See <https://spec.commonmark.org/0.30/#example-601>

**Comment by Witiko** [comment]
The corresponding unit test is `testfiles/CommonMark_0.30/autolinks/009.test`:

``````````` md
%   ---RESULT--- "example": 601,
%   
%   <p>&lt;http://foo.bar/baz bim&gt;</p>
%   
%   ---\RESULT---

<<<
<http://foo.bar/baz bim>
>>>
documentBegin
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/autolinks/009.test"`:

```````````
Testfile testfiles/CommonMark_0.30/autolinks/009.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command pdftex   --shell-escape                  --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-22 12:00:20.513155514 +0100
--- test-actual.log	2022-12-22 12:00:27.053100362 +0100
***************
*** 1,2 ****
--- 1,7 ----
  documentBegin
+ BEGIN link
+ - label: http://foo.bar/baz bim
+ - URI: http://foo.bar/baz bim
+ - title: 
+ END link
  documentEnd
```````````

The issue seems related to the PEG patterns for parsing [autolinks][1], which use the rules for [Gruber's Markdown][2] rather than [CommonMark][3].

 [1]: https://github.com/Witiko/markdown/blob/e9aa96e399ef59929c2c161f85d324a5378d8db5/markdown.dtx#L21983-L22005
 [2]: https://daringfireball.net/projects/markdown/syntax#autolink
 [3]: https://spec.commonmark.org/0.30/#autolinks
