### ISSUE TITLE
Blockquotes can contain link references

### ISSUE THREAD

**Issue by lostenderman** [lostenderman/markdown#100]
See <https://spec.commonmark.org/0.30/#example-218>

**Comment by Witiko** [comment]
The corresponding unit test is `testfiles/CommonMark_0.30/link_reference_definitions/027.test`:

``````````` md
%   ---RESULT--- "example": 218,
%   
%   <p><a href="/url">foo</a></p>
%   <blockquote>
%   </blockquote>
%   
%   ---\RESULT---

<<<
[foo]

> [foo]: /url
>>>
documentBegin
BEGIN link
- label: foo
- URI: /url
- title: 
END link
interblockSeparator
blockQuoteBegin
blockQuoteEnd
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/link_reference_definitions/027.test"`:

```````````
Testfile testfiles/CommonMark_0.30/link_reference_definitions/027.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command luatex                                   --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-19 11:33:51.441745556 +0100
--- test-actual.log	2022-12-19 11:33:57.201725566 +0100
***************
*** 5,10 ****
  - title: 
  END link
  interblockSeparator
- blockQuoteBegin
- blockQuoteEnd
  documentEnd
--- 5,8 ----
```````````

The issue seems related to the fact that [the blockquote writer][1] will omit the surrounding `blockQuoteBegin` and `blockQuoteEnd` if the body of the blockquote is empty.

 [1]: https://github.com/Witiko/markdown/blob/e9aa96e399ef59929c2c161f85d324a5378d8db5/markdown.dtx#L20709
