### ISSUE TITLE
Link labels can contain escaped backslashes

### ISSUE THREAD

**Issue by lostenderman** [lostenderman/markdown#103]
See <https://spec.commonmark.org/0.30/#example-549>

**Comment by Witiko** [comment]
The corresponding unit test is `testfiles/CommonMark_0.30/links/069.test`:

``````````` md
%   ---RESULT--- "example": 549,
%   
%   <p><a href="/uri">bar\</a></p>
%   
%   ---\RESULT---

<<<
[bar\\]: /uri

[bar\\]
>>>
documentBegin
BEGIN link
- label: bar(backslash)
- URI: /uri
- title: 
END link
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/links/069.test"`:

```````````
Testfile testfiles/CommonMark_0.30/links/069.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command luatex                                   --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-19 11:33:25.331832519 +0100
--- test-actual.log	2022-12-19 11:33:31.791811571 +0100
***************
*** 1,7 ****
  documentBegin
! BEGIN link
! - label: bar(backslash)
! - URI: /uri
! - title: 
! END link
  documentEnd
--- 1,5 ----
  documentBegin
! backslash
! interblockSeparator
! backslash
  documentEnd
```````````

The issue seems related to [the `parsers.tag` PEG pattern][1], which is used to parse [indirect links][2] and which fails to account for double backslashes.

 [1]: https://github.com/Witiko/markdown/blob/e9aa96e399ef59929c2c161f85d324a5378d8db5/markdown.dtx#L21317-L21325
 [2]: https://github.com/Witiko/markdown/blob/e9aa96e399ef59929c2c161f85d324a5378d8db5/markdown.dtx#L22015-L22016
