### ISSUE TITLE
Link reference definition without a reference should produce no output

### ISSUE THREAD

**Issue by lostenderman** [lostenderman/markdown#105]
See <https://spec.commonmark.org/0.30/#example-210> with link destination emphasised

**Comment by Witiko** [comment]
The corresponding unit test is `testfiles/CommonMark_0.30/link_reference_definitions/019.test`:

``````````` md
%   ---RESULT--- "example": 210,
%   
%   <p>&quot;title&quot; <em>ok</em></p>
%   
%   ---\RESULT---

<<<
[foo]: /*url*
"title" *ok*
>>>
documentBegin
emphasis: ok
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/link_reference_definitions/019.test"`:

```````````
Testfile testfiles/CommonMark_0.30/link_reference_definitions/019.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command pdftex   --shell-escape                  --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-16 13:15:19.614137152 +0100
--- test-actual.log	2022-12-16 13:15:26.374078995 +0100
***************
*** 1,3 ****
--- 1,4 ----
  documentBegin
+ emphasis: url
  emphasis: ok
  documentEnd
```````````

The issue seems related to [the PEG patterns for parsing reference definitions][1], which expects a blank line after the end of a reference (i.e. between `[foo]: /*url*` and `"title" *ok*` in our unit test).

To try and fix the issue, you would:

1. Modify `markdown.dtx`.
2. [Reinstall markdown][2].
3. Rerun `./test.sh "testfiles/CommonMark_0.30/link_reference_definitions/019.test"`.

 [1]: https://github.com/Witiko/markdown/blob/e9aa96e399ef59929c2c161f85d324a5378d8db5/markdown.dtx#L21477-L21487
 [2]: https://witiko.github.io/markdown/#installation
