### ISSUE TITLE
Non-matching backticks in a code span should produce literal backticks

### ISSUE THREAD

**Issue by lostenderman** [lostenderman/markdown#18]
See <https://spec.commonmark.org/0.30/#example-347>

**Comment by Witiko** [comment]
The corresponding unit test is `testfiles/CommonMark_0.30/code_spans/020.test`:

``````````` md
%   ---RESULT--- "example": 347,
%   
%   <p>```foo``</p>
%   
%   ---\RESULT---

<<<
```foo``
>>>
documentBegin
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/code_spans/020.test"`:

```````````
Testfile testfiles/CommonMark_0.30/code_spans/020.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command pdftex   --shell-escape                  --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-22 11:58:53.043894103 +0100
--- test-actual.log	2022-12-22 11:58:59.643838308 +0100
***************
*** 1,2 ****
--- 1,3 ----
  documentBegin
+ codeSpan: foo
  documentEnd
```````````

The issue seems related to the PEG patterns for parsing code spans ([1][], [2][]), which use the rules for [Gruber's Markdown][3] rather than [CommonMark][4].

Since [the function `captures_equal_length()`][5] should ensure that only backticks of equal length are matched, I was curious where the extra backtick went and I investigated the TeX output:

```
$ cat _markdown_test/1a7d570185be4954038cebd9eb645730.md.tex
\markdownRendererDocumentBegin
`\markdownRendererCodeSpan{foo}\markdownRendererDocumentEnd
```

This indicates that the leading backtick is interpreted as a line character and does not prevent any upcoming backticks from being part of a code span.

[The `walkable_syntax.Inline` rule][6] will try matching [the `parsers.Str` PEG pattern][7] first and will only match [the `parsers.Symbol` PEG pattern][8] as a last resort. The `parsers.Str` PEG pattern matches all non-special characters, whereas the `parsers.Symbol` pattern will match special characters, [including backticks][9]. In the above example, the leading backtick was matched using the `parsers.Symbol` PEG pattern. Therefore, it seems that we need to add an exception to the `parsers.Symbol` PEG pattern and have it consume any number of backticks rather than just a single backtick, which should prevent any immediately following code span from being matched.

This issue has inspired pull request https://github.com/Witiko/markdown/pull/239, which improves the speed of parsing. Unless I overlooked something, the fix suggested above should not interact with this change and should work regardless of whether you merge the latest upstream `main` branch into the `commonmark` branch or not.

 [1]: https://github.com/Witiko/markdown/blob/9530198735bec755abe75b9f93f8c664d57aa6f8/markdown.dtx#L21636-L21663
 [2]: https://github.com/Witiko/markdown/blob/9530198735bec755abe75b9f93f8c664d57aa6f8/markdown.dtx#L22350
 [3]: https://daringfireball.net/projects/markdown/syntax#code
 [4]: https://spec.commonmark.org/0.30/#code-spans
 [5]: https://github.com/Witiko/markdown/blob/9530198735bec755abe75b9f93f8c664d57aa6f8/markdown.dtx#L21646-L21648
 [6]: https://github.com/Witiko/markdown/blob/9530198735bec755abe75b9f93f8c664d57aa6f8/markdown.dtx#L1644-L1662
 [7]: https://github.com/Witiko/markdown/blob/9530198735bec755abe75b9f93f8c664d57aa6f8/markdown.dtx#L22340-L22341
 [8]: https://github.com/Witiko/markdown/blob/9530198735bec755abe75b9f93f8c664d57aa6f8/markdown.dtx#L22343-L22344
 [9]: https://github.com/Witiko/markdown/blob/9530198735bec755abe75b9f93f8c664d57aa6f8/markdown.dtx#L22846
