### ISSUE TITLE
A left-flanking delimiter run is a delimiter run that is (1) not followed by Unicode whitespace, and either (2a) not followed by a Unicode punctuation character, or (2b) followed by a Unicode punctuation character and preceded by Unicode whitespace or a Unicode punctuation character

### ISSUE THREAD

**Issue by lostenderman** [lostenderman/markdown#20]
See <https://spec.commonmark.org/0.30/#left-flanking-delimiter-run>

**Comment by Witiko** [comment]
What is the issue and how can we reproduce it?

**Comment by lostenderman** [comment]
Neither emphasis nor strong emphasis should be produced in the following examples.

For emphasis, see:

<https://spec.commonmark.org/0.30/#example-352>
<https://spec.commonmark.org/0.30/#example-358>
<https://spec.commonmark.org/0.30/#example-367>

```
a*"foo"* 
a_"foo"_
*(*foo)
```

For strong emphasis, see:

<https://spec.commonmark.org/0.30/#example-378>
<https://spec.commonmark.org/0.30/#example-379>
<https://spec.commonmark.org/0.30/#example-382>
<https://spec.commonmark.org/0.30/#example-384>
<https://spec.commonmark.org/0.30/#example-391>

```
a**"foo"**
a__"foo"__
**(**foo)
** foo bar**
__ foo bar__
```

**Comment by Witiko** [comment]
The corresponding unit tests are:

- `testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/003.test` (example 352)
- `testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/009.test` (example 358)
- `testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/029.test` (example 378)
- `testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/030.test` (example 379)
- `testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/035.test` (example 384)
- `testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/042.test` (example 391)

The issue seems related to the PEG patterns for parsing [emphasis and strong emphasis][1], which use the rules for [Gruber's Markdown][2] rather than [CommonMark][3].

 [1]: https://github.com/Witiko/markdown/blob/9530198735bec755abe75b9f93f8c664d57aa6f8/markdown.dtx#L22410-L22430
 [2]: https://daringfireball.net/projects/markdown/syntax#em
 [3]: https://spec.commonmark.org/0.30/#emphasis-and-strong-emphasis

# `testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/003.test`

``````````` md
%   ---RESULT--- "example": 352,
%   
%   <p>a*&quot;foo&quot;*</p>
%   
%   ---\RESULT---

<<<
a*"foo"*
>>>
documentBegin
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/003.test"`:

```````````
Testfile testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/003.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command pdftex   --shell-escape                  --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-22 12:01:19.022662414 +0100
--- test-actual.log	2022-12-22 12:01:25.822605151 +0100
***************
*** 1,2 ****
--- 1,3 ----
  documentBegin
+ emphasis: "foo"
  documentEnd
```````````

# `testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/009.test`

``````````` md
%   ---RESULT--- "example": 358,
%   
%   <p>a_&quot;foo&quot;_</p>
%   
%   ---\RESULT---

<<<
a_"foo"_
>>>
documentBegin
underscore
underscore
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/009.test"`:

```````````
Testfile testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/009.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command pdftex   --shell-escape                  --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-22 12:01:26.552599004 +0100
--- test-actual.log	2022-12-22 12:01:33.282542340 +0100
***************
*** 1,4 ****
  documentBegin
! underscore
! underscore
  documentEnd
--- 1,3 ----
  documentBegin
! emphasis: "foo"
  documentEnd
```````````

# `testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/029.test`

``````````` md
%   ---RESULT--- "example": 378,
%   
%   <p>** foo bar**</p>
%   
%   ---\RESULT---

<<<
** foo bar**
>>>
documentBegin
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/029.test"`:

```````````
Testfile testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/029.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command luatex                                   --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-30 22:40:29.015526131 +0100
--- test-actual.log	2022-12-30 22:40:36.035440965 +0100
***************
*** 1,2 ****
--- 1,3 ----
  documentBegin
+ emphasis: * foo bar
  documentEnd
```````````

# `testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/030.test`

``````````` md
%   ---RESULT--- "example": 379,
%   
%   <p>a**&quot;foo&quot;**</p>
%   
%   ---\RESULT---

<<<
a**"foo"**
>>>
documentBegin
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/030.test"`:

```````````
Testfile testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/030.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command luatex                                   --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-30 22:41:29.594803704 +0100
--- test-actual.log	2022-12-30 22:41:35.834730838 +0100
***************
*** 1,2 ****
--- 1,3 ----
  documentBegin
+ strongEmphasis: "foo"
  documentEnd
```````````

# `testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/035.test`

``````````` md
%   ---RESULT--- "example": 384,
%   
%   <p>a__&quot;foo&quot;__</p>
%   
%   ---\RESULT---

<<<
a__"foo"__
>>>
documentBegin
underscore
underscore
underscore
underscore
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/035.test"`:

```````````
Testfile testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/035.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command luatex                                   --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-30 22:42:08.534353424 +0100
--- test-actual.log	2022-12-30 22:42:14.654283592 +0100
***************
*** 1,6 ****
  documentBegin
! underscore
! underscore
! underscore
! underscore
  documentEnd
--- 1,3 ----
  documentBegin
! strongEmphasis: "foo"
  documentEnd
```````````

# `testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/042.test`

``````````` md
%   ---RESULT--- "example": 391,
%   
%   <p>**(**foo)</p>
%   
%   ---\RESULT---

<<<
**(**foo)
>>>
documentBegin
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/042.test"`:

```````````
Testfile testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/042.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command luatex                                   --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-30 22:53:06.207812029 +0100
--- test-actual.log	2022-12-30 22:53:12.287757500 +0100
***************
*** 1,2 ****
--- 1,3 ----
  documentBegin
+ strongEmphasis: (
  documentEnd
```````````
