### ISSUE TITLE
A right-flanking delimiter run is a delimiter run that is (1) not preceded by Unicode whitespace, and either (2a) not preceded by a Unicode punctuation character, or (2b) preceded by a Unicode punctuation character and followed by Unicode whitespace or a Unicode punctuation character

### ISSUE THREAD

**Issue by lostenderman** [lostenderman/markdown#23]
See <https://spec.commonmark.org/0.30/#right-flanking-delimiter-run>

**Comment by lostenderman** [comment]
Neither emphasis nor strong emphasis should be produced in the following examples.

For emphasis, see:

<https://spec.commonmark.org/0.30/#example-365>
<https://spec.commonmark.org/0.30/#example-367>
<https://spec.commonmark.org/0.30/#example-370>
<https://spec.commonmark.org/0.30/#example-371>

```
*foo bar *
*(*foo)
_foo bar _
_(_foo)
```

For strong emphasis, see:

<https://spec.commonmark.org/0.30/#example-390>
<https://spec.commonmark.org/0.30/#example-391>
<https://spec.commonmark.org/0.30/#example-396>
<https://spec.commonmark.org/0.30/#example-397>

```
**foo bar **
**(**foo)
__foo bar __
__(__foo)
```

**Comment by Witiko** [comment]
The corresponding unit tests are:

- `testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/018.test` (example 367)
- `testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/022.test` (example 371)
- `testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/041.test` (example 390)
- `testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/042.test` (example 391)
- `testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/047.test` (example 396)
- `testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/048.test` (example 397)

The issue seems related to the PEG patterns for parsing [emphasis and strong emphasis][1], which use the rules for [Gruber's Markdown][2] rather than [CommonMark][3].

 [1]: https://github.com/Witiko/markdown/blob/9530198735bec755abe75b9f93f8c664d57aa6f8/markdown.dtx#L22410-L22430
 [2]: https://daringfireball.net/projects/markdown/syntax#em
 [3]: https://spec.commonmark.org/0.30/#emphasis-and-strong-emphasis

# `testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/018.test`

``````````` md
%   ---RESULT--- "example": 367,
%   
%   <p>*(*foo)</p>
%   
%   ---\RESULT---

<<<
*(*foo)
>>>
documentBegin
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/018.test"`:

```````````
Testfile testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/018.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command luatex                                   --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-30 20:30:34.824378546 +0100
--- test-actual.log	2022-12-30 20:30:40.944311784 +0100
***************
*** 1,2 ****
--- 1,3 ----
  documentBegin
+ emphasis: (
  documentEnd
```````````

# `testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/022.test`

``````````` md
%   ---RESULT--- "example": 371,
%   
%   <p>_(_foo)</p>
%   
%   ---\RESULT---

<<<
_(_foo)
>>>
documentBegin
underscore
underscore
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/022.test"`:

```````````
Testfile testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/022.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command luatex                                   --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-30 20:31:05.304047101 +0100
--- test-actual.log	2022-12-30 20:31:11.393981188 +0100
***************
*** 1,4 ****
  documentBegin
! underscore
! underscore
  documentEnd
--- 1,3 ----
  documentBegin
! emphasis: (
  documentEnd
```````````

# `testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/041.test`

``````````` md
%   ---RESULT--- "example": 390,
%   
%   <p>**foo bar **</p>
%   
%   ---\RESULT---

<<<
**foo bar **
>>>
documentBegin
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/041.test"`:

```````````
Testfile testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/041.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command luatex                                   --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-30 20:31:51.813546209 +0100
--- test-actual.log	2022-12-30 20:31:58.033479644 +0100
***************
*** 1,2 ****
--- 1,3 ----
  documentBegin
+ emphasis: foo bar *
  documentEnd
```````````

# `testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/042.test`

``````````` md
%   ---RESULT--- "example": 391,
%   
%   <p>**(**foo)</p>
%   
%   ---\RESULT---

<<<
**(**foo)
>>>
documentBegin
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/042.test"`:

```````````
Testfile testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/042.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command luatex                                   --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-30 20:32:31.273125517 +0100
--- test-actual.log	2022-12-30 20:32:37.433060177 +0100
***************
*** 1,2 ****
--- 1,3 ----
  documentBegin
+ strongEmphasis: (
  documentEnd
```````````

# `testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/047.test`

``````````` md
%   ---RESULT--- "example": 396,
%   
%   <p>__foo bar __</p>
%   
%   ---\RESULT---

<<<
__foo bar __
>>>
documentBegin
underscore
underscore
underscore
underscore
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/047.test"`:

```````````
Testfile testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/047.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command luatex                                   --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-30 20:33:18.792623668 +0100
--- test-actual.log	2022-12-30 20:33:24.602562647 +0100
***************
*** 1,6 ****
  documentBegin
  underscore
! underscore
! underscore
! underscore
  documentEnd
--- 1,4 ----
  documentBegin
  underscore
! emphasis: foo bar (underscore)
  documentEnd
```````````

# `testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/048.test`

``````````` md
%   ---RESULT--- "example": 397,
%   
%   <p>__(__foo)</p>
%   
%   ---\RESULT---

<<<
__(__foo)
>>>
documentBegin
underscore
underscore
underscore
underscore
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/048.test"`:

```````````
Testfile testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/048.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command luatex                                   --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-30 20:33:57.562217786 +0100
--- test-actual.log	2022-12-30 20:34:03.712153679 +0100
***************
*** 1,6 ****
  documentBegin
! underscore
! underscore
! underscore
! underscore
  documentEnd
--- 1,3 ----
  documentBegin
! strongEmphasis: (
  documentEnd
```````````
