### ISSUE TITLE
A delimiter that can both open and close cannot form emphasis if the sum of the lengths of the delimiter runs containing the opening and closing delimiters is a multiple of 3 unless both lengths are multiples of 3

### ISSUE THREAD

**Issue by lostenderman** [lostenderman/markdown#24]
See <https://spec.commonmark.org/0.30/#example-411>

**Comment by Witiko** [comment]
The corresponding unit test is `testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/062.test`:

``````````` md
%   ---RESULT--- "example": 411,
%   
%   <p><em>foo**bar</em></p>
%   
%   ---\RESULT---

<<<
*foo**bar*
>>>
documentBegin
emphasis: foo**bar
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/062.test"`:

```````````
Testfile testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/062.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command pdftex   --shell-escape                  --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-22 11:58:31.494076361 +0100
--- test-actual.log	2022-12-22 11:58:37.914022051 +0100
***************
*** 1,3 ****
  documentBegin
! emphasis: foo**bar
  documentEnd
--- 1,4 ----
  documentBegin
! emphasis: foo
! emphasis: bar
  documentEnd
```````````

The issue seems related to the PEG patterns for parsing [emphasis and strong emphasis][1], which use the rules for [Gruber's Markdown][2] rather than [CommonMark][3].

 [1]: https://github.com/Witiko/markdown/blob/9530198735bec755abe75b9f93f8c664d57aa6f8/markdown.dtx#L22410-L22430
 [2]: https://daringfireball.net/projects/markdown/syntax#em
 [3]: https://spec.commonmark.org/0.30/#emphasis-and-strong-emphasis
