### ISSUE TITLE
Emphasis and strong emphasis can be nested inside strong emphasis

### ISSUE THREAD

**Issue by lostenderman** [lostenderman/markdown#25]
See <https://spec.commonmark.org/0.30/#example-425>

**Comment by Witiko** [comment]
The corresponding unit test is `testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/074.test`:

``````````` md
%   ---RESULT--- "example": 423,
%   
%   <p><strong>foo <em>bar</em> baz</strong></p>
%   
%   ---\RESULT---

<<<
__foo _bar_ baz__
>>>
documentBegin
strongEmphasis: foo (emphasis: bar) baz
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/074.test"`:

```````````
Testfile testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/074.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command pdftex   --shell-escape                  --interaction=nonstopmode  test.tex
      Command xetex    --shell-escape --8bit           --interaction=nonstopmode  test.tex
      Command luatex                                   --interaction=nonstopmode  test.tex
    Template templates/plain/verbatim.tex.m4
      Command pdftex   --shell-escape                  --interaction=nonstopmode  test.tex
      Command xetex    --shell-escape --8bit           --interaction=nonstopmode  test.tex
      Command luatex                                   --interaction=nonstopmode  test.tex
```````````

I cannot reproduce any issues.

**Comment by lostenderman** [comment]
The wrong example was referenced.

Example https://spec.commonmark.org/0.30/#example-425; however, does fail.

The description has been updated accordingly.

**Comment by Witiko** [comment]
The corresponding unit test is `testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/076.test`:

``````````` md
%   ---RESULT--- "example": 425,
%   
%   <p><strong><strong>foo</strong> bar</strong></p>
%   
%   ---\RESULT---

<<<
____foo__ bar__
>>>
documentBegin
strongEmphasis: (strongEmphasis: foo) bar
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/076.test"`:

```````````
Testfile testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/076.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command luatex                                   --interaction=nonstopmode  test.tex
*** test-expected.log	2023-01-01 01:11:10.943096966 +0100
--- test-actual.log	2023-01-01 01:11:17.033046637 +0100
***************
*** 1,3 ****
  documentBegin
! strongEmphasis: (strongEmphasis: foo) bar
  documentEnd
--- 1,8 ----
  documentBegin
! underscore
! underscore
! underscore
! underscore
! emphasis: (underscore) bar
! underscore
  documentEnd
```````````

The issue seems related to the PEG patterns for parsing [emphasis and strong emphasis][1], which use the rules for [Gruber's Markdown][2] rather than [CommonMark][3].

 [1]: https://github.com/Witiko/markdown/blob/9530198735bec755abe75b9f93f8c664d57aa6f8/markdown.dtx#L22410-L22430
 [2]: https://daringfireball.net/projects/markdown/syntax#em
 [3]: https://spec.commonmark.org/0.30/#emphasis-and-strong-emphasis
