### ISSUE TITLE
When delimiters do not match evenly, Rule 11 determines that the excess literal * characters will appear outside of the emphasis, rather than inside it

### ISSUE THREAD

**Issue by lostenderman** [lostenderman/markdown#27]
See <https://spec.commonmark.org/0.30/#example-444> and <https://spec.commonmark.org/0.30/#example-446>

**Comment by Witiko** [comment]
The corresponding unit test is `testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/092.test`:

``````````` md
%   ---RESULT--- "example": 441,
%   
%   <p>*<em>foo</em></p>
%   
%   ---\RESULT---

<<<
**foo*
>>>
documentBegin
emphasis: foo
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/092.test"`:

```````````
Testfile testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/092.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command pdftex   --shell-escape                  --interaction=nonstopmode  test.tex
      Command xetex    --shell-escape --8bit           --interaction=nonstopmode  test.tex
      Command luatex                                   --interaction=nonstopmode  test.tex
    Template templates/plain/verbatim.tex.m4
      Command pdftex   --shell-escape                  --interaction=nonstopmode  test.tex
      Command xetex    --shell-escape --8bit           --interaction=nonstopmode  test.tex
      Command luatex                                   --interaction=nonstopmode  test.tex
```````````

I cannot reproduce any issues.

**Comment by lostenderman** [comment]
The wrong example was referenced.

Examples https://spec.commonmark.org/0.30/#example-444 https://spec.commonmark.org/0.30/#example-446; however, do fail due to the reason specified above.

The description has been updated accordingly.

**Comment by Witiko** [comment]
The corresponding unit tests are:

- `testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/095.test` (example 444)
- `testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/097.test` (example 446)

The issue seems related to the PEG patterns for parsing [emphasis and strong emphasis][1], which use the rules for [Gruber's Markdown][2] rather than [CommonMark][3].

 [1]: https://github.com/Witiko/markdown/blob/9530198735bec755abe75b9f93f8c664d57aa6f8/markdown.dtx#L22410-L22430
 [2]: https://daringfireball.net/projects/markdown/syntax#em
 [3]: https://spec.commonmark.org/0.30/#emphasis-and-strong-emphasis

# `testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/095.test`

``````````` md
%   ---RESULT--- "example": 444,
%   
%   <p>***<em>foo</em></p>
%   
%   ---\RESULT---

<<<
****foo*
>>>
documentBegin
emphasis: foo
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/095.test"`:

```````````
Testfile testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/095.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command luatex                                   --interaction=nonstopmode  test.tex
*** test-expected.log	2023-01-01 01:08:38.434357853 +0100
--- test-actual.log	2023-01-01 01:08:44.614306739 +0100
***************
*** 1,3 ****
  documentBegin
- emphasis: foo
  documentEnd
--- 1,2 ----
```````````

# `testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/097.test`

``````````` md
%   ---RESULT--- "example": 446,
%   
%   <p><em>foo</em>***</p>
%   
%   ---\RESULT---

<<<
*foo****
>>>
documentBegin
emphasis: foo
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/097.test"`:

```````````
Testfile testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/097.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command luatex                                   --interaction=nonstopmode  test.tex
*** test-expected.log	2023-01-01 01:09:12.794073690 +0100
--- test-actual.log	2023-01-01 01:09:18.594025728 +0100
***************
*** 1,3 ****
--- 1,4 ----
  documentBegin
  emphasis: foo
+ emphasis: *
  documentEnd
```````````
