### ISSUE TITLE
At least one space or tab is required between the # characters and the heading’s contents

### ISSUE THREAD

**Issue by lostenderman** [lostenderman/markdown#3]
See <https://spec.commonmark.org/0.30/#example-64>

**Comment by Witiko** [comment]
The corresponding unit test is `testfiles/CommonMark_0.30/atx_headings/003.test`:

``````````` md
%   ---RESULT--- "example": 64,
%   
%   <p>#5 bolt</p>
%   <p>#hashtag</p>
%   
%   ---\RESULT---

<<<
#5 bolt

#hashtag
>>>
documentBegin
hash
interblockSeparator
hash
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/atx_headings/003.test"`:

```````````
Testfile testfiles/CommonMark_0.30/atx_headings/003.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command pdftex   --shell-escape                  --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-22 12:00:57.052847486 +0100
--- test-actual.log	2022-12-22 12:01:03.512793058 +0100
***************
*** 1,5 ****
  documentBegin
! hash
  interblockSeparator
! hash
  documentEnd
--- 1,5 ----
  documentBegin
! headingOne: 5 bolt
  interblockSeparator
! headingOne: hashtag
  documentEnd
```````````

The issue seems related to the PEG patterns for parsing headings ([1][], [2][]), which use the rules for [Gruber's Markdown][3] rather than [CommonMark][4].

 [1]: https://github.com/Witiko/markdown/blob/4bdde2988a54ad53346323ee3b5298b9e57d6633/markdown.dtx#L21528-L21548
 [2]: https://github.com/Witiko/markdown/blob/4bdde2988a54ad53346323ee3b5298b9e57d6633/markdown.dtx#L22179-L22208
 [3]: https://daringfireball.net/projects/markdown/syntax#header
 [4]: https://spec.commonmark.org/0.30/#atx-headings
