### ISSUE TITLE
Strong emphasis within strong emphasis is possible without switching delimiters

### ISSUE THREAD

**Issue by lostenderman** [lostenderman/markdown#30]
See <https://spec.commonmark.org/0.30/#example-463>

**Comment by Witiko** [comment]
The corresponding unit test is `testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/114.test`:

``````````` md
%   ---RESULT--- "example": 463,
%   
%   <p><strong><strong>foo</strong></strong></p>
%   
%   ---\RESULT---

<<<
****foo****
>>>
documentBegin
strongEmphasis: (strongEmphasis: foo)
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/114.test"`:

```````````
Testfile testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/114.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command pdftex   --shell-escape                  --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-22 11:56:20.735185156 +0100
--- test-actual.log	2022-12-22 11:56:27.295129400 +0100
***************
*** 1,3 ****
  documentBegin
- strongEmphasis: (strongEmphasis: foo)
  documentEnd
--- 1,2 ----
```````````

The issue seems related to the PEG patterns for parsing [emphasis and strong emphasis][1], which use the rules for [Gruber's Markdown][2] rather than [CommonMark][3].

 [1]: https://github.com/Witiko/markdown/blob/9530198735bec755abe75b9f93f8c664d57aa6f8/markdown.dtx#L22410-L22430
 [2]: https://daringfireball.net/projects/markdown/syntax#em
 [3]: https://spec.commonmark.org/0.30/#emphasis-and-strong-emphasis
