### ISSUE TITLE
An interpretation <em><strong>...</strong></em> is always preferred to <strong><em>...</em></strong>

### ISSUE THREAD

**Issue by lostenderman** [lostenderman/markdown#32]
See <https://spec.commonmark.org/0.30/#example-466>

**Comment by Witiko** [comment]
The corresponding unit test is `testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/117.test`:

``````````` md
%   ---RESULT--- "example": 466,
%   
%   <p><em><strong>foo</strong></em></p>
%   
%   ---\RESULT---

<<<
***foo***
>>>
documentBegin
emphasis: (strongEmphasis: foo)
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/117.test"`:

```````````
Testfile testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/117.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command pdftex   --shell-escape                  --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-22 11:56:06.525305986 +0100
--- test-actual.log	2022-12-22 11:56:12.765252917 +0100
***************
*** 1,3 ****
  documentBegin
! emphasis: (strongEmphasis: foo)
  documentEnd
--- 1,3 ----
  documentBegin
! strongEmphasis: (emphasis: foo)
  documentEnd
```````````

The issue seems related to the PEG patterns for parsing [emphasis and strong emphasis][1], which use the rules for [Gruber's Markdown][2] rather than [CommonMark][3]. Fixing this issue may need changes to [the `walkable_syntax.Inline` table][7], which determines the precedence of inline elements.

 [1]: https://github.com/Witiko/markdown/blob/9530198735bec755abe75b9f93f8c664d57aa6f8/markdown.dtx#L22410-L22430
 [2]: https://daringfireball.net/projects/markdown/syntax#em
 [3]: https://spec.commonmark.org/0.30/#emphasis-and-strong-emphasis
 [7]: https://github.com/Witiko/markdown/blob/e9aa96e399ef59929c2c161f85d324a5378d8db5/markdown.dtx#L1626-L1667
