### ISSUE TITLE
When two potential emphasis or strong emphasis spans overlap, so that the second begins before the first ends and ends after the first ends, the first takes precedence.

### ISSUE THREAD

**Issue by lostenderman** [lostenderman/markdown#33]
See <https://spec.commonmark.org/0.30/#example-468>

**Comment by Witiko** [comment]
The corresponding unit test is `testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/119.test`:

``````````` md
%   ---RESULT--- "example": 468,
%   
%   <p><em>foo _bar</em> baz_</p>
%   
%   ---\RESULT---

<<<
*foo _bar* baz_
>>>
documentBegin
emphasis: foo (underscore)bar
underscore
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/119.test"`:

```````````
Testfile testfiles/CommonMark_0.30/emphasis_and_strong_emphasis/119.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command pdftex   --shell-escape                  --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-22 11:55:59.245367916 +0100
--- test-actual.log	2022-12-22 11:56:05.855311685 +0100
***************
*** 1,4 ****
  documentBegin
! emphasis: foo (underscore)bar
! underscore
  documentEnd
--- 1,3 ----
  documentBegin
! emphasis: bar* baz
  documentEnd
```````````

The issue seems related to the PEG patterns for parsing [emphasis and strong emphasis][1], which use the rules for [Gruber's Markdown][2] rather than [CommonMark][3].

 [1]: https://github.com/Witiko/markdown/blob/9530198735bec755abe75b9f93f8c664d57aa6f8/markdown.dtx#L22410-L22430
 [2]: https://daringfireball.net/projects/markdown/syntax#em
 [3]: https://spec.commonmark.org/0.30/#emphasis-and-strong-emphasis
