### ISSUE TITLE
Code point U+0000 should be replaced by U+FFFD

### ISSUE THREAD

**Issue by lostenderman** [lostenderman/markdown#34]
See <https://spec.commonmark.org/0.30/#example-26>

**Comment by Witiko** [comment]
@lostenderman, can you please assign this issue to me? I will tackle this together with the normalization of newlines in issue #42.

**Comment by lostenderman** [comment]
Not closing issue with pull #117.

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/entity_and_numeric_character_references/002.test"`:

```
Testfile testfiles/CommonMark_0.30/entity_and_numeric_character_references/002.test
  Format templates/context/
    Template templates/context/input.tex.m4
      Command texexec  --passon="--shell-escape --8bit --interaction=nonstopmode" test.tex
      Command context                                              --nonstopmode  test.tex
        Command terminated with exit code 1.
*** test-expected.log   2023-01-13 18:07:23.417953900 +0100
--- test-actual.log     2023-01-13 18:07:24.717953900 +0100
***************
*** 1,3 ****
  documentBegin
- emphasis: (hash) Ӓ Ϡ �
- documentEnd
--- 1 ----
```

**Comment by Witiko** [comment]
@lostenderman Interesting. Looks like a SIGSEGV on the first glance, which would indicate that there is some vulnerability in LuaTeX that we have uncovered. I will investigate.

**Comment by Witiko** [comment]
Dear LuaTeX developers,

assume the following plain TeX document `example.tex`:

    \newwrite\outfile
    \openout\outfile\jobname.out
    \write\outfile{^^^^fffd}
    \closeout\outfile
    \bye

Running `luatex example` will correctly produce file `example.out` with the
UTF-8 encoding of U+FFFD: 0xEF, 0xBF, and 0xBD.

    $ hexdump -C
    00000000  ef bf bd 0a                                       |....|
    00000004

Now, let's change `example.tex` as follows:

    \input\jobname.out
    \bye

Running `luatex example` produces the following error:

    ! String contains an invalid utf-8 sequence.

I would expect that LuaTeX would treat ^^^^fffd and the byte sequence 0xEF,
0xBF, and 0xBD the same. This issue was co-discovered by @lostenderman at
<https://github.com/lostenderman/markdown/issues/34>.

Best,
Vitek

**Comment by Witiko** [comment]
@lostenderman https://github.com/lostenderman/markdown/pull/119 should close this issue.

**Comment by lostenderman** [comment]
Closing with pull #119.
