### ISSUE TITLE
An image description may have inline elements as its contents

### ISSUE THREAD

**Issue by lostenderman** [lostenderman/markdown#39]
See <https://spec.commonmark.org/0.30/#example-572>

**Comment by Witiko** [comment]
The corresponding unit test is `testfiles/CommonMark_0.30/images/002.test`:

``````````` md
%   ---RESULT--- "example": 572,
%   
%   <p><img src="train.jpg" alt="foo bar" title="train &amp; tracks" /></p>
%   
%   ---\RESULT---

<<<
![foo *bar*]

[foo *bar*]: train.jpg "train & tracks"
>>>
documentBegin
BEGIN image
- label: foo (emphasis: bar)
- URI: train.jpg
- title: train (ampersand) tracks
END image
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/images/002.test"`:

```````````
Testfile testfiles/CommonMark_0.30/images/002.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command pdftex   --shell-escape                  --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-22 11:54:57.405894794 +0100
--- test-actual.log	2022-12-22 11:55:03.735840793 +0100
***************
*** 1,6 ****
  documentBegin
  BEGIN image
! - label: foo (emphasis: bar)
  - URI: train.jpg
  - title: train (ampersand) tracks
  END image
--- 1,6 ----
  documentBegin
  BEGIN image
! - label: foo *bar*
  - URI: train.jpg
  - title: train (ampersand) tracks
  END image
```````````

The issue seems related to the PEG patterns for parsing direct and indirect links and images ([1][], [2][]), which use the rules for Gruber's Markdown ([3][], [4][]) rather than CommonMark ([5][], [6][]).

 [1]: https://github.com/Witiko/markdown/blob/e9aa96e399ef59929c2c161f85d324a5378d8db5/markdown.dtx#L21279-L21355
 [2]: https://github.com/Witiko/markdown/blob/e9aa96e399ef59929c2c161f85d324a5378d8db5/markdown.dtx#L22007-L22033
 [3]: https://daringfireball.net/projects/markdown/syntax#link
 [4]: https://daringfireball.net/projects/markdown/syntax#img
 [5]: https://spec.commonmark.org/0.30/#links
 [6]: https://spec.commonmark.org/0.30/#images
