### ISSUE TITLE
Pointy brackets that enclose links must be unescaped

### ISSUE THREAD

**Issue by lostenderman** [lostenderman/markdown#48]
See <https://spec.commonmark.org/0.30/#example-492>

**Comment by Witiko** [comment]
The corresponding unit test is `testfiles/CommonMark_0.30/links/012.test`:

``````````` md
%   ---RESULT--- "example": 492,
%   
%   <p>[link](&lt;foo&gt;)</p>
%   
%   ---\RESULT---

<<<
[link](<foo\>)
>>>
documentBegin
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/links/012.test"`:

```````````
Testfile testfiles/CommonMark_0.30/links/012.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command pdftex   --shell-escape                  --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-22 11:53:29.176649288 +0100
--- test-actual.log	2022-12-22 11:53:35.406595895 +0100
***************
*** 1,2 ****
--- 1,7 ----
  documentBegin
+ BEGIN link
+ - label: link
+ - URI: <foo>
+ - title: 
+ END link
  documentEnd
```````````

The issue seems related to the PEG patterns for parsing [autolink][1], which use the rules for [Gruber's Markdown][2] rather than [CommonMark][3].

 [1]: https://github.com/Witiko/markdown/blob/e9aa96e399ef59929c2c161f85d324a5378d8db5/markdown.dtx#L21983-L22005
 [2]: https://daringfireball.net/projects/markdown/syntax#autolink
 [3]: https://spec.commonmark.org/0.30/#autolinks
