### ISSUE TITLE
The closing sequence in a heading must be preceded by a space or tab

### ISSUE THREAD

**Issue by lostenderman** [lostenderman/markdown#5]
See <https://spec.commonmark.org/0.30/#example-75>

**Comment by Witiko** [comment]
The corresponding unit test is `testfiles/CommonMark_0.30/atx_headings/014.test`:

``````````` md
%   ---RESULT--- "example": 75,
%   
%   <h1>foo#</h1>
%   
%   ---\RESULT---

<<<
# foo#
>>>
documentBegin
headingOne: foo(hash)
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/atx_headings/014.test"`:

```````````
Testfile testfiles/CommonMark_0.30/atx_headings/014.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command pdftex   --shell-escape                  --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-22 12:00:42.312971709 +0100
--- test-actual.log	2022-12-22 12:00:48.682918020 +0100
***************
*** 1,3 ****
  documentBegin
! headingOne: foo(hash)
  documentEnd
--- 1,3 ----
  documentBegin
! headingOne: foo
  documentEnd
```````````

The issue seems related to the PEG patterns for parsing headings ([1][], [2][]), which use the rules for [Gruber's Markdown][3] rather than [CommonMark][4].

 [1]: https://github.com/Witiko/markdown/blob/4bdde2988a54ad53346323ee3b5298b9e57d6633/markdown.dtx#L21528-L21548
 [2]: https://github.com/Witiko/markdown/blob/4bdde2988a54ad53346323ee3b5298b9e57d6633/markdown.dtx#L22179-L22208
 [3]: https://daringfireball.net/projects/markdown/syntax#header
 [4]: https://spec.commonmark.org/0.30/#atx-headings
