### ISSUE TITLE
The link text may contain balanced brackets, but not unbalanced ones, unless they are escaped

### ISSUE THREAD

**Issue by lostenderman** [lostenderman/markdown#52]
See <https://spec.commonmark.org/0.30/#example-514>

**Comment by Witiko** [comment]
The corresponding unit test is `testfiles/CommonMark_0.30/links/031.test`:

``````````` md
%   ---RESULT--- "example": 511,
%   
%   <p><a href="/uri">link [foo [bar]]</a></p>
%   
%   ---\RESULT---

<<<
[link [foo [bar]]](/uri)
>>>
documentBegin
BEGIN link
- label: link [foo [bar]]
- URI: /uri
- title: 
END link
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/links/031.test"`:

```````````
Testfile testfiles/CommonMark_0.30/links/031.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command pdftex   --shell-escape                  --interaction=nonstopmode  test.tex
      Command xetex    --shell-escape --8bit           --interaction=nonstopmode  test.tex
      Command luatex                                   --interaction=nonstopmode  test.tex
    Template templates/plain/verbatim.tex.m4
      Command pdftex   --shell-escape                  --interaction=nonstopmode  test.tex
      Command xetex    --shell-escape --8bit           --interaction=nonstopmode  test.tex
      Command luatex                                   --interaction=nonstopmode  test.tex
```````````

I cannot reproduce any issues.

**Comment by lostenderman** [comment]
The wrong example was referenced.

Example https://spec.commonmark.org/0.30/#example-514; however, does fail due to the reason specified above.

The description has been updated accordingly.

**Comment by Witiko** [comment]
The corresponding unit test is `testfiles/CommonMark_0.30/links/034.test`:

``````````` md
%   ---RESULT--- "example": 514,
%   
%   <p><a href="/uri">link [bar</a></p>
%   
%   ---\RESULT---

<<<
[link \[bar](/uri)
>>>
documentBegin
BEGIN link
- label: link [bar
- URI: /uri
- title: 
END link
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/links/034.test"`:

```````````
Testfile testfiles/CommonMark_0.30/links/034.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command luatex                                   --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-29 21:57:42.344435208 +0100
--- test-actual.log	2022-12-29 21:57:48.474372698 +0100
***************
*** 1,7 ****
  documentBegin
- BEGIN link
- - label: link [bar
- - URI: /uri
- - title: 
- END link
  documentEnd
--- 1,2 ----
```````````

The issue seems related to the PEG patterns for parsing direct and indirect links and images ([1][], [2][]), which use the rules for Gruber's Markdown ([3][], [4][]) rather than CommonMark ([5][], [6][]).

 [1]: https://github.com/Witiko/markdown/blob/e9aa96e399ef59929c2c161f85d324a5378d8db5/markdown.dtx#L21279-L21355
 [2]: https://github.com/Witiko/markdown/blob/e9aa96e399ef59929c2c161f85d324a5378d8db5/markdown.dtx#L22007-L22033
 [3]: https://daringfireball.net/projects/markdown/syntax#link
 [4]: https://daringfireball.net/projects/markdown/syntax#img
 [5]: https://spec.commonmark.org/0.30/#links
 [6]: https://spec.commonmark.org/0.30/#images
