### ISSUE TITLE
Links may not contain other links, at any level of nesting

### ISSUE THREAD

**Issue by lostenderman** [lostenderman/markdown#53]
See <https://spec.commonmark.org/0.30/#example-519>

**Comment by Witiko** [comment]
The corresponding unit test is `testfiles/CommonMark_0.30/links/039.test`:

``````````` md
%   ---RESULT--- "example": 519,
%   
%   <p><img src="uri3" alt="[foo](uri2)" /></p>
%   
%   ---\RESULT---

<<<
![[[foo](uri1)](uri2)](uri3)
>>>
documentBegin
BEGIN image
- label: [(BEGIN link)(- label: foo)(- URI: uri1)(- title: )(END link)](uri2)
- URI: uri3
- title: 
END image
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/links/039.test"`:

```````````
Testfile testfiles/CommonMark_0.30/links/039.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command pdftex   --shell-escape                  --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-22 11:52:25.967192129 +0100
--- test-actual.log	2022-12-22 11:52:32.227138274 +0100
***************
*** 1,6 ****
  documentBegin
  BEGIN image
! - label: [(BEGIN link)(- label: foo)(- URI: uri1)(- title: )(END link)](uri2)
  - URI: uri3
  - title: 
  END image
--- 1,6 ----
  documentBegin
  BEGIN image
! - label: (BEGIN link)(- label: [foo](uri1))(- URI: uri2)(- title: )(END link)
  - URI: uri3
  - title: 
  END image
```````````

The issue seems related to the PEG patterns for parsing direct and indirect links and images ([1][], [2][]), which use the rules for Gruber's Markdown ([3][], [4][]) rather than CommonMark ([5][], [6][]).

 [1]: https://github.com/Witiko/markdown/blob/e9aa96e399ef59929c2c161f85d324a5378d8db5/markdown.dtx#L21279-L21355
 [2]: https://github.com/Witiko/markdown/blob/e9aa96e399ef59929c2c161f85d324a5378d8db5/markdown.dtx#L22007-L22033
 [3]: https://daringfireball.net/projects/markdown/syntax#link
 [4]: https://daringfireball.net/projects/markdown/syntax#img
 [5]: https://spec.commonmark.org/0.30/#links
 [6]: https://spec.commonmark.org/0.30/#images
