### ISSUE TITLE
Unicode case fold is used

### ISSUE THREAD

**Issue by lostenderman** [lostenderman/markdown#56]
See <https://spec.commonmark.org/0.30/#example-539>

**Comment by Witiko** [comment]
The corresponding unit test is `testfiles/CommonMark_0.30/links/059.test`:

``````````` md
%   ---RESULT--- "example": 539,
%   
%   <p><a href="/url">ẞ</a></p>
%   
%   ---\RESULT---

<<<
[ẞ]

[SS]: /url
>>>
documentBegin
BEGIN link
- label: ẞ
- URI: /url
- title: 
END link
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/links/059.test"`:

```````````
Testfile testfiles/CommonMark_0.30/links/059.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command pdftex   --shell-escape                  --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-22 11:52:04.127380188 +0100
--- test-actual.log	2022-12-22 11:52:10.727323328 +0100
***************
*** 1,7 ****
  documentBegin
- BEGIN link
- - label: ẞ
- - URI: /url
- - title: 
- END link
  documentEnd
--- 1,2 ----
```````````

**Comment by Witiko** [comment]
This issue seems related to [the `reader->normalize_tag()` method][1], which normalizes tags for references, indirect links and images, and notes. Currently, we use the Unicode-unaware `string.lower()` method. For Unicode-aware transformations, we [currently use][2] either [the Selene Unicode library][5] or [the `utf8` built-in library][4] of Lua 5.3 and 5.4 if Selene Unicode is unavailable (at strange platforms such as [LuaMetaTeX][3]).

The `utf8` built-in library has no support for Unicode case. Selene Unicode only supports ([1][6], [2][7]) Unicode-aware lower-casing and upper-casing, which is [different from case-folding][8]. This leads me to believe that we cannot currently comply with this requirement, although we can at least use the `unicode.utf8.lower()` method when Selene Unicode is available and only [polyfill it][2] with `string.lower()` when Selene Unicode is unavailable. We should document that this is best-effort, remove unit test `testfiles/CommonMark_0.30/links/059.test`, and ask for directions on [the LuaTeX mailing list][9].

 [1]: https://github.com/Witiko/markdown/blob/main/markdown.dtx#L22061-L22078
 [2]: https://github.com/Witiko/markdown/blob/faae5ab22cee6b4b37eb4d85ea99162ded90f61b/markdown.dtx#L1049-L1080
 [3]: http://www.pragma-ade.nl/general/manuals/luametatex.pdf#page=17
 [4]: https://q-syshelp.qsc.com/Content/Control_Scripting/Lua_5.3_Reference_Manual/Standard_Libraries/4_-_Basic_UTF-8_Support.htm
 [5]: https://web.archive.org/web/20200627193026/http://luaforge.net/projects/sln/
 [6]: https://github.com/LuaDist/slnunicode/blob/e8abd35c5f0f5a9084442d8665cbc9c3d169b5fd/slnunico.c#L1285-L1302
 [7]: https://www.pragma-ade.com/general/manuals/luatex.pdf#page=66
 [8]: https://unicode.org/faq/casemap_charprop.html#2
 [9]: https://tug.org/mailman/listinfo/luatex

**Comment by Witiko** [comment]
LaTeX3 implements case folding, see `\str_casefold:n` in [LaTeX3 interfaces][1]. However, using LaTeX3 would require that we resolve indirect links in the TeX layer rather than during parsing in low-level Lua.

 [1]: https://www.ctan.org/pkg/l3kernel

**Comment by Witiko** [comment]
I digged around a bit and it seems that [LaTeX3 actually reads `UnicodeData.txt`][1] to implement case-folding and does all the heavy lifting. This seems to be one of the rare cases, where it is easier to do data processing in `\TeX` than it is in Lua. Perhaps we could load `UnicodeData.txt` from the Markdown package and do case folding ourselves (after asking around [the LuaTeX mailing list][2] to see if we are reinventing wheels)?

Note that there is a cost associated with loading `UnicodeData.txt` and we may load the Markdown package many times in older TeX engines such as pdfTeX, where we have to use the ANSI C `system()` call to access Lua. Therefore, we would prefer to do this lazily and invoke case-fold only when we do not find a match using exact matching and ASCII lower-casing.

@lostenderman, can you please assign this issue to me?

 [1]: https://github.com/latex3/latex3/blob/d1001f2738cf1423e50486707def96166024361d/l3kernel/l3unicode.dtx#L699-L715
 [2]: https://tug.org/mailman/listinfo/luatex

**Comment by Witiko** [comment]
> However, using LaTeX3 would require that we resolve indirect links in the TeX layer rather than during parsing in low-level Lua.

As discussed in today's call, the Lua parser needs to keep track of the reference definitions, so that it can produce the correct parse tree. For example, there is no way to construct a parse tree for `[foo][bar][baz] without knowing the reference definitions, see also [example 569][1].

Therefore, implementing case-folding in Lua seems as the only option.

 [1]: https://spec.commonmark.org/0.30/#example-569

**Comment by Witiko** [comment]
> However, using LaTeX3 would require that we resolve indirect links in the TeX layer rather than during parsing in low-level Lua.

As discussed in today's call, this is impossible without moving parts of the parser to TeX. For example, the parse tree of `[foo][bar][baz]` is ambiguous unless we know the reference definitions, see also [CommonMark example 569][1].

 [1]: https://spec.commonmark.org/0.30/#example-569

**Comment by Witiko** [comment]
I posted [a question][4] at TeX StackExchange:

> I would like to perform [Unicode case-folding][1] in LuaTeX.
> 
> Can you suggest whether there is an existing implementation available
> in TeX Live, or whether I should implement the case-folding algorithm
> myself using the `UnicodeData.txt` and `CaseFolding.txt` files as a part
> of [the unicode-data package][3] in TeX Live?
> 
> As a side note: LaTeX3 implements case-folding as TeX commands, see
> function `\str_casefold:n` in [LaTeX3 interfaces][2]. I would find it
> somewhat amusing if it would be easier to case-fold a string in TeX than
> it would be in Lua.

 [1]: https://www.unicode.org/versions/Unicode15.0.0/ch05.pdf#page=43
 [2]: http://mirrors.ctan.org/macros/latex/contrib/l3kernel/interface3.pdf#page=142
 [3]: https://ctan.org/pkg/unicode-data
 [4]: https://tex.stackexchange.com/q/672649/70941
