### ISSUE TITLE
When there are multiple matching link reference definitions, the first is used

### ISSUE THREAD

**Issue by lostenderman** [lostenderman/markdown#58]
See <https://spec.commonmark.org/0.30/#example-543>

**Comment by Witiko** [comment]
The corresponding unit test is `testfiles/CommonMark_0.30/links/063.test`:

``````````` md
%   ---RESULT--- "example": 543,
%   
%   <p><a href="/url1">bar</a></p>
%   
%   ---\RESULT---

<<<
[foo]: /url1

[foo]: /url2

[bar][foo]
>>>
documentBegin
BEGIN link
- label: bar
- URI: /url1
- title: 
END link
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/links/063.test"`:

```````````
Testfile testfiles/CommonMark_0.30/links/063.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command pdftex   --shell-escape                  --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-22 11:51:50.147500710 +0100
--- test-actual.log	2022-12-22 11:51:56.457446297 +0100
***************
*** 1,7 ****
  documentBegin
  BEGIN link
  - label: bar
! - URI: /url1
  - title: 
  END link
  documentEnd
--- 1,7 ----
  documentBegin
  BEGIN link
  - label: bar
! - URI: /url2
  - title: 
  END link
  documentEnd
```````````

The issue seems related to [the `register_link()` function][1], which uses the last reference definition rather than the first. Similarly, we should update [the `register_note()` function][2], which does the same for [notes][3].

 [1]: https://github.com/Witiko/markdown/blob/e9aa96e399ef59929c2c161f85d324a5378d8db5/markdown.dtx#L21822-L21826
 [2]: https://github.com/Witiko/markdown/blob/e9aa96e399ef59929c2c161f85d324a5378d8db5/markdown.dtx#L23550-L23553
 [3]: https://witiko.github.io/markdown/#option-notes
