### ISSUE TITLE
Link labels cannot contain brackets, unless they are backslash-escaped

### ISSUE THREAD

**Issue by lostenderman** [lostenderman/markdown#59]
See <https://spec.commonmark.org/0.30/#example-546> and <https://spec.commonmark.org/0.30/#example-547>

**Comment by Witiko** [comment]
The corresponding unit test is `testfiles/CommonMark_0.30/links/065.test`:

``````````` md
%   ---RESULT--- "example": 545,
%   
%   <p>[foo][ref[]</p>
%   <p>[ref[]: /uri</p>
%   
%   ---\RESULT---

<<<
[foo][ref[]

[ref[]: /uri
>>>
documentBegin
interblockSeparator
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/links/065.test"`:

```````````
Testfile testfiles/CommonMark_0.30/links/065.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command pdftex   --shell-escape                  --interaction=nonstopmode  test.tex
      Command xetex    --shell-escape --8bit           --interaction=nonstopmode  test.tex
      Command luatex                                   --interaction=nonstopmode  test.tex
    Template templates/plain/verbatim.tex.m4
      Command pdftex   --shell-escape                  --interaction=nonstopmode  test.tex
      Command xetex    --shell-escape --8bit           --interaction=nonstopmode  test.tex
      Command luatex                                   --interaction=nonstopmode  test.tex
```````````

I cannot reproduce any issues.

**Comment by lostenderman** [comment]
The wrong example was referenced.

Examples https://spec.commonmark.org/0.30/#example-546 and https://spec.commonmark.org/0.30/#example-547; however, do fail due to the reason specified above.

The description has been updated accordingly.

**Comment by Witiko** [comment]
The corresponding unit tests are:

- `testfiles/CommonMark_0.30/links/066.test` (example 546)
- `testfiles/CommonMark_0.30/links/067.test` (example 547)

The issue seems related to the PEG patterns for parsing direct and indirect links and images ([1][], [2][]), which use the rules for Gruber's Markdown ([3][], [4][]) rather than CommonMark ([5][], [6][]).

 [1]: https://github.com/Witiko/markdown/blob/e9aa96e399ef59929c2c161f85d324a5378d8db5/markdown.dtx#L21279-L21355
 [2]: https://github.com/Witiko/markdown/blob/e9aa96e399ef59929c2c161f85d324a5378d8db5/markdown.dtx#L22007-L22033
 [3]: https://daringfireball.net/projects/markdown/syntax#link
 [4]: https://daringfireball.net/projects/markdown/syntax#img
 [5]: https://spec.commonmark.org/0.30/#links
 [6]: https://spec.commonmark.org/0.30/#images

# `testfiles/CommonMark_0.30/links/066.test`

``````````` md
%   ---RESULT--- "example": 546,
%   
%   <p>[foo][ref[bar]]</p>
%   <p>[ref[bar]]: /uri</p>
%   
%   ---\RESULT---

<<<
[foo][ref[bar]]

[ref[bar]]: /uri
>>>
documentBegin
interblockSeparator
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/links/066.test"`:

```````````
Testfile testfiles/CommonMark_0.30/links/066.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command luatex                                   --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-29 21:52:57.807366497 +0100
--- test-actual.log	2022-12-29 21:53:03.717304901 +0100
***************
*** 1,3 ****
  documentBegin
! interblockSeparator
  documentEnd
--- 1,7 ----
  documentBegin
! BEGIN link
! - label: foo
! - URI: /uri
! - title: 
! END link
  documentEnd
```````````

# `testfiles/CommonMark_0.30/links/067.test`

``````````` md
%   ---RESULT--- "example": 547,
%   
%   <p>[[[foo]]]</p>
%   <p>[[[foo]]]: /url</p>
%   
%   ---\RESULT---

<<<
[[[foo]]]

[[[foo]]]: /url
>>>
documentBegin
interblockSeparator
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/links/067.test"`:

```````````
Testfile testfiles/CommonMark_0.30/links/067.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command luatex                                   --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-29 21:53:28.497047020 +0100
--- test-actual.log	2022-12-29 21:53:34.356986124 +0100
***************
*** 1,3 ****
  documentBegin
! interblockSeparator
  documentEnd
--- 1,7 ----
  documentBegin
! BEGIN link
! - label: [[foo]]
! - URI: /url
! - title: 
! END link
  documentEnd
```````````
