### ISSUE TITLE
A link label must contain at least one character that is not a space, tab, or line ending

### ISSUE THREAD

**Issue by lostenderman** [lostenderman/markdown#60]
See <https://spec.commonmark.org/0.30/#example-550>

**Comment by Witiko** [comment]
The corresponding unit test is `testfiles/CommonMark_0.30/links/070.test`:

``````````` md
%   ---RESULT--- "example": 550,
%   
%   <p>[]</p>
%   <p>[]: /uri</p>
%   
%   ---\RESULT---

<<<
[]

[]: /uri
>>>
documentBegin
interblockSeparator
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/links/070.test"`:

```````````
Testfile testfiles/CommonMark_0.30/links/070.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command pdftex   --shell-escape                  --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-22 11:51:04.037899066 +0100
--- test-actual.log	2022-12-22 11:51:10.357844387 +0100
***************
*** 1,3 ****
  documentBegin
! interblockSeparator
  documentEnd
--- 1,7 ----
  documentBegin
! BEGIN link
! - label: 
! - URI: /uri
! - title: 
! END link
  documentEnd
```````````

The issue seems related to the PEG patterns for parsing direct and indirect links and images ([1][], [2][]), which use the rules for Gruber's Markdown ([3][], [4][]) rather than CommonMark ([5][], [6][]).

 [1]: https://github.com/Witiko/markdown/blob/e9aa96e399ef59929c2c161f85d324a5378d8db5/markdown.dtx#L21279-L21355
 [2]: https://github.com/Witiko/markdown/blob/e9aa96e399ef59929c2c161f85d324a5378d8db5/markdown.dtx#L22007-L22033
 [3]: https://daringfireball.net/projects/markdown/syntax#link
 [4]: https://daringfireball.net/projects/markdown/syntax#img
 [5]: https://spec.commonmark.org/0.30/#links
 [6]: https://spec.commonmark.org/0.30/#images
