### ISSUE TITLE
If a link text consists of multiple invalid link labels, the last is used, others are parsed as text

### ISSUE THREAD

**Issue by lostenderman** [lostenderman/markdown#61]
See <https://spec.commonmark.org/0.30/#example-568>

**Comment by Witiko** [comment]
The corresponding unit test is `testfiles/CommonMark_0.30/links/088.test`:

``````````` md
%   ---RESULT--- "example": 568,
%   
%   <p>[foo]<a href="/url">bar</a></p>
%   
%   ---\RESULT---

<<<
[foo][bar][baz]

[baz]: /url
>>>
documentBegin
BEGIN link
- label: bar
- URI: /url
- title: 
END link
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/links/088.test"`:

```````````
Testfile testfiles/CommonMark_0.30/links/088.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command pdftex   --shell-escape                  --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-22 11:50:56.677962775 +0100
--- test-actual.log	2022-12-22 11:51:03.367904864 +0100
***************
*** 1,6 ****
  documentBegin
  BEGIN link
! - label: bar
  - URI: /url
  - title: 
  END link
--- 1,6 ----
  documentBegin
  BEGIN link
! - label: baz
  - URI: /url
  - title: 
  END link
```````````

The issue seems related to the PEG patterns for parsing direct and indirect links and images ([1][], [2][]), which use the rules for Gruber's Markdown ([3][], [4][]) rather than CommonMark ([5][], [6][]).

 [1]: https://github.com/Witiko/markdown/blob/e9aa96e399ef59929c2c161f85d324a5378d8db5/markdown.dtx#L21279-L21355
 [2]: https://github.com/Witiko/markdown/blob/e9aa96e399ef59929c2c161f85d324a5378d8db5/markdown.dtx#L22007-L22033
 [3]: https://daringfireball.net/projects/markdown/syntax#link
 [4]: https://daringfireball.net/projects/markdown/syntax#img
 [5]: https://spec.commonmark.org/0.30/#links
 [6]: https://spec.commonmark.org/0.30/#images
