### ISSUE TITLE
Ordered list start numbers must be nine digits or less

### ISSUE THREAD

**Issue by lostenderman** [lostenderman/markdown#64]
See <https://spec.commonmark.org/0.30/#example-266>

**Comment by Witiko** [comment]
The corresponding unit test is `testfiles/CommonMark_0.30/list_items/014.test`:

``````````` md
%   ---RESULT--- "example": 266,
%   
%   <p>1234567890. <em>not ok</em></p>
%   
%   ---\RESULT---

<<<
1234567890. _not ok_
>>>
documentBegin
emphasis: not ok
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/list_items/014.test"`:

```````````
Testfile testfiles/CommonMark_0.30/list_items/014.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command luatex                                   --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-29 12:24:45.492112183 +0100
--- test-actual.log	2022-12-29 12:24:52.262062207 +0100
***************
*** 1,3 ****
--- 1,7 ----
  documentBegin
+ olBeginTight
+ olItemWithNumber: 1234567890
  emphasis: not ok
+ olItemEnd
+ olEndTight
  documentEnd
```````````

The issue seems related to the PEG patterns for parsing lists ([1][], [2][]), which use the rules for [Gruber's Markdown][3], rather than [CommonMark][4]. Specifically, the issue seems related to [the `parsers.enumerator` PEG pattern][5].

 [1]: https://github.com/Witiko/markdown/blob/e9aa96e399ef59929c2c161f85d324a5378d8db5/markdown.dtx#L21766-L21794
 [2]: https://github.com/Witiko/markdown/blob/e9aa96e399ef59929c2c161f85d324a5378d8db5/markdown.dtx#L22093-L22170
 [3]: https://daringfireball.net/projects/markdown/syntax#list
 [4]: https://spec.commonmark.org/0.30/#lists
 [5]: https://github.com/Witiko/markdown/blob/e9aa96e399ef59929c2c161f85d324a5378d8db5/markdown.dtx#L21780-L21791
