### ISSUE TITLE
5 spaces are enough to produce a code block in the first item in a list

### ISSUE THREAD

**Issue by lostenderman** [lostenderman/markdown#65]
See <https://spec.commonmark.org/0.30/#example-273>

**Comment by Witiko** [comment]
The corresponding unit test is `testfiles/CommonMark_0.30/list_items/021.test`:

``````````` md
%   ---RESULT--- "example": 273,
%   
%   <ol>
%   <li>
%   <pre><code>indented code
%   </code></pre>
%   <p>paragraph</p>
%   <pre><code>more code
%   </code></pre>
%   </li>
%   </ol>
%   
%   ---\RESULT---

<<<
1.     indented code

   paragraph

       more code
>>>
documentBegin
olBegin
olItemWithNumber: 1
inputVerbatim: ./_markdown_test/bf995e3b2610078e871b00000c1fb65f.verbatim
interblockSeparator
interblockSeparator
inputVerbatim: ./_markdown_test/edf19530665eedd599d1228679ec3a65.verbatim
olItemEnd
olEnd
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/list_items/021.test"`:

```````````
Testfile testfiles/CommonMark_0.30/list_items/021.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command luatex                                   --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-29 12:23:48.372533206 +0100
--- test-actual.log	2022-12-29 12:23:56.542473058 +0100
***************
*** 1,10 ****
  documentBegin
! olBegin
  olItemWithNumber: 1
! inputVerbatim: ./_markdown_test/bf995e3b2610078e871b00000c1fb65f.verbatim
  interblockSeparator
  interblockSeparator
! inputVerbatim: ./_markdown_test/edf19530665eedd599d1228679ec3a65.verbatim
! olItemEnd
! olEnd
  documentEnd
--- 1,9 ----
  documentBegin
! olBeginTight
  olItemWithNumber: 1
! olItemEnd
! olEndTight
  interblockSeparator
  interblockSeparator
! inputVerbatim: ./_markdown_test/a813bd3049b4c04b87aca0e8cf1f8fcb.verbatim
  documentEnd
```````````

The issue seems related to the PEG patterns for parsing lists ([1][], [2][]), which handle indents in lists using the rules for [Gruber's Markdown][3], rather than [CommonMark][4]. This may also be related to [the PEG patterns for parsing code blocks][5].

 [1]: https://github.com/Witiko/markdown/blob/e9aa96e399ef59929c2c161f85d324a5378d8db5/markdown.dtx#L21766-L21794
 [2]: https://github.com/Witiko/markdown/blob/e9aa96e399ef59929c2c161f85d324a5378d8db5/markdown.dtx#L22093-L22170
 [3]: https://daringfireball.net/projects/markdown/syntax#list
 [4]: https://spec.commonmark.org/0.30/#lists
 [5]: https://github.com/Witiko/markdown/blob/faae5ab22cee6b4b37eb4d85ea99162ded90f61b/markdown.dtx#L22515-L22517
