### ISSUE TITLE
A . character or a ) can be used in ordered list markers

### ISSUE THREAD

**Issue by lostenderman** [lostenderman/markdown#67]
See <https://spec.commonmark.org/0.30/#ordered-list-marker>

**Comment by Witiko** [comment]
What is the issue and how can we reproduce it?

**Comment by lostenderman** [comment]
See <https://spec.commonmark.org/0.30/#example-296>. Character `)` should also be able to produce `markdownRendererOlItemWithNumber` similarly to how `.` does.

**Comment by Witiko** [comment]
The corresponding unit test is `testfiles/CommonMark_0.30/list_items/044.test`:

``````````` md
%   ---RESULT--- "example": 296,
%   
%   <ol start="10">
%   <li><em>foo</em>
%   <ul>
%   <li><em>bar</em></li>
%   </ul>
%   </li>
%   </ol>
%   
%   ---\RESULT---

<<<
10) _foo_
    - _bar_
>>>
documentBegin
olBeginTight
olItemWithNumber: 10
emphasis: foo
interblockSeparator
ulBeginTight
ulItem
emphasis: bar
ulItemEnd
ulEndTight
olItemEnd
olEndTight
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/list_items/044.test"`:

```````````
Testfile testfiles/CommonMark_0.30/list_items/044.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command pdftex   --shell-escape                  --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-22 12:01:04.192787329 +0100
--- test-actual.log	2022-12-22 12:01:10.922730636 +0100
***************
*** 1,13 ****
  documentBegin
- olBeginTight
- olItemWithNumber: 10
  emphasis: foo
- interblockSeparator
- ulBeginTight
- ulItem
  emphasis: bar
- ulItemEnd
- ulEndTight
- olItemEnd
- olEndTight
  documentEnd
--- 1,4 ----
```````````

The issue seems related to the PEG patterns for parsing lists ([1][], [2][]), which use the rules for [Gruber's Markdown][3], rather than [CommonMark][4].

 [1]: https://github.com/Witiko/markdown/blob/e9aa96e399ef59929c2c161f85d324a5378d8db5/markdown.dtx#L21766-L21794
 [2]: https://github.com/Witiko/markdown/blob/e9aa96e399ef59929c2c161f85d324a5378d8db5/markdown.dtx#L22093-L22170
 [3]: https://daringfireball.net/projects/markdown/syntax#list
 [4]: https://spec.commonmark.org/0.30/#lists
