### ISSUE TITLE
Changing the bullet or ordered list delimiter starts a new list

### ISSUE THREAD

**Issue by lostenderman** [lostenderman/markdown#69]
See <https://spec.commonmark.org/0.30/#example-301>

**Comment by Witiko** [comment]
The corresponding unit test is `testfiles/CommonMark_0.30/lists/001.test`:

``````````` md
%   ---RESULT--- "example": 301,
%   
%   <ul>
%   <li><em>foo</em></li>
%   <li><em>bar</em></li>
%   </ul>
%   <ul>
%   <li><em>baz</em></li>
%   </ul>
%   
%   ---\RESULT---

<<<
- _foo_
- _bar_
+ _baz_
>>>
documentBegin
ulBeginTight
ulItem
emphasis: foo
ulItemEnd
ulItem
emphasis: bar
ulItemEnd
ulEndTight
interblockSeparator
ulBeginTight
ulItem
emphasis: baz
ulItemEnd
ulEndTight
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/lists/001.test"`:

```````````
Testfile testfiles/CommonMark_0.30/lists/001.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command pdftex   --shell-escape                  --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-22 11:49:10.338887519 +0100
--- test-actual.log	2022-12-22 11:49:16.628832583 +0100
***************
*** 6,14 ****
  ulItem
  emphasis: bar
  ulItemEnd
- ulEndTight
- interblockSeparator
- ulBeginTight
  ulItem
  emphasis: baz
  ulItemEnd
--- 6,11 ----
```````````

The issue seems related to the PEG patterns for parsing lists ([1][], [2][]), which use the rules for [Gruber's Markdown][3], rather than [CommonMark][4].

 [1]: https://github.com/Witiko/markdown/blob/e9aa96e399ef59929c2c161f85d324a5378d8db5/markdown.dtx#L21766-L21794
 [2]: https://github.com/Witiko/markdown/blob/e9aa96e399ef59929c2c161f85d324a5378d8db5/markdown.dtx#L22093-L22170
 [3]: https://daringfireball.net/projects/markdown/syntax#list
 [4]: https://spec.commonmark.org/0.30/#lists
