### ISSUE TITLE
No blank line is needed to separate a paragraph from a following list

### ISSUE THREAD

**Issue by lostenderman** [lostenderman/markdown#70]
See <https://spec.commonmark.org/0.30/#example-303>

**Comment by Witiko** [comment]
The corresponding unit test is `testfiles/CommonMark_0.30/lists/003.test`:

``````````` md
%   ---RESULT--- "example": 303,
%   
%   <p><em>Foo</em></p>
%   <ul>
%   <li><em>bar</em></li>
%   <li><em>baz</em></li>
%   </ul>
%   
%   ---\RESULT---

<<<
_Foo_
- _bar_
- _baz_
>>>
documentBegin
emphasis: Foo
interblockSeparator
ulBeginTight
ulItem
emphasis: bar
ulItemEnd
ulItem
emphasis: baz
ulItemEnd
ulEndTight
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/lists/003.test"`:

```````````
Testfile testfiles/CommonMark_0.30/lists/003.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command pdftex   --shell-escape                  --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-22 11:49:03.048951228 +0100
--- test-actual.log	2022-12-22 11:49:09.668893372 +0100
***************
*** 1,12 ****
  documentBegin
  emphasis: Foo
- interblockSeparator
- ulBeginTight
- ulItem
  emphasis: bar
- ulItemEnd
- ulItem
  emphasis: baz
- ulItemEnd
- ulEndTight
  documentEnd
--- 1,5 ----
```````````

The issue seems related to the PEG patterns for parsing lists ([1][], [2][]), which use the rules for [Gruber's Markdown][3], rather than [CommonMark][4].

Similarly to options [`blankBeforeBlockquote`][5], [`blankBeforeCodeFence`][6], [`blankBeforeDivFence`][7], and [`blankBeforeHeading`][8], we should add option `blankBeforeList` with default value of `false`, which would control this behavior. See also https://github.com/Witiko/markdown/issues/29.

 [1]: https://github.com/Witiko/markdown/blob/e9aa96e399ef59929c2c161f85d324a5378d8db5/markdown.dtx#L21766-L21794
 [2]: https://github.com/Witiko/markdown/blob/e9aa96e399ef59929c2c161f85d324a5378d8db5/markdown.dtx#L22093-L22170
 [3]: https://daringfireball.net/projects/markdown/syntax#list
 [4]: https://spec.commonmark.org/0.30/#lists

 [5]: https://witiko.github.io/markdown/#option-blankbeforeblockquote
 [6]: https://witiko.github.io/markdown/#option-blankbeforecodefence
 [7]: https://witiko.github.io/markdown/#option-blankbeforedivfence
 [8]: https://witiko.github.io/markdown/#option-blankbeforeheading
