### ISSUE TITLE
List items need not be indented to the same level. The following list items will be treated as items at the same list level

### ISSUE THREAD

**Issue by lostenderman** [lostenderman/markdown#73]
See <https://spec.commonmark.org/0.30/#example-311>

**Comment by lostenderman** [comment]
The wrong example was referenced.

Example https://spec.commonmark.org/0.30/#example-311; however, does fail due to the reason specified above.

The description has been updated accordingly.

**Comment by Witiko** [comment]
The corresponding unit test is `testfiles/CommonMark_0.30/lists/011.test`:

``````````` md
%   ---RESULT--- "example": 311,
%   
%   <ol>
%   <li>
%   <p><em>a</em></p>
%   </li>
%   <li>
%   <p><em>b</em></p>
%   </li>
%   <li>
%   <p><em>c</em></p>
%   </li>
%   </ol>
%   
%   ---\RESULT---

<<<
1. _a_

  2. _b_

   3. _c_
>>>
documentBegin
olBegin
olItemWithNumber: 1
emphasis: a
olItemEnd
olItemWithNumber: 2
emphasis: b
olItemEnd
olItemWithNumber: 3
emphasis: c
olItemEnd
olEnd
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/lists/011.test"`:

```````````
Testfile testfiles/CommonMark_0.30/lists/011.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command luatex                                   --interaction=nonstopmode  test.tex
*** test-expected.log	2023-01-01 00:29:48.003804529 +0100
--- test-actual.log	2023-01-01 00:29:55.033747571 +0100
***************
*** 6,13 ****
  olItemWithNumber: 2
  emphasis: b
  olItemEnd
- olItemWithNumber: 3
- emphasis: c
- olItemEnd
  olEnd
  documentEnd
--- 6,12 ----
  olItemWithNumber: 2
  emphasis: b
  olItemEnd
  olEnd
+ interblockSeparator
+ emphasis: c
  documentEnd
```````````

The issue seems related to the PEG patterns for parsing lists ([1][], [2][]), which handle indents in lists using the rules for [Gruber's Markdown][3], rather than [CommonMark][4].

 [1]: https://github.com/Witiko/markdown/blob/e9aa96e399ef59929c2c161f85d324a5378d8db5/markdown.dtx#L21766-L21794
 [2]: https://github.com/Witiko/markdown/blob/e9aa96e399ef59929c2c161f85d324a5378d8db5/markdown.dtx#L22093-L22170
 [3]: https://daringfireball.net/projects/markdown/syntax#list
 [4]: https://spec.commonmark.org/0.30/#lists
