### ISSUE TITLE
List items may not be preceded by more than three spaces of indentation

### ISSUE THREAD

**Issue by lostenderman** [lostenderman/markdown#74]
See <https://spec.commonmark.org/0.30/#example-312>

**Comment by Witiko** [comment]
The corresponding unit test is `testfiles/CommonMark_0.30/lists/012.test`:

``````````` md
%   ---RESULT--- "example": 312,
%   
%   <ul>
%   <li><em>a</em></li>
%   <li><em>b</em></li>
%   <li><em>c</em></li>
%   <li><em>d</em>
%   - <em>e</em></li>
%   </ul>
%   
%   ---\RESULT---

<<<
- _a_
 - _b_
  - _c_
   - _d_
    - _e_
>>>
documentBegin
ulBeginTight
ulItem
emphasis: a
ulItemEnd
ulItem
emphasis: b
ulItemEnd
ulItem
emphasis: c
ulItemEnd
ulItem
emphasis: d
emphasis: e
ulItemEnd
ulEndTight
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/lists/012.test"`:

```````````
Testfile testfiles/CommonMark_0.30/lists/012.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command pdftex   --shell-escape                  --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-22 11:47:38.309695169 +0100
--- test-actual.log	2022-12-22 11:47:44.619639547 +0100
***************
*** 11,17 ****
--- 11,22 ----
  ulItemEnd
  ulItem
  emphasis: d
+ interblockSeparator
+ ulBeginTight
+ ulItem
  emphasis: e
  ulItemEnd
  ulEndTight
+ ulItemEnd
+ ulEndTight
  documentEnd
```````````

The issue seems related to [the PEG patterns for parsing lists][1], which handle indents in lists using the rules for [Gruber's Markdown][2] rather than [CommonMark][3].

 [1]: https://github.com/Witiko/markdown/blob/e9aa96e399ef59929c2c161f85d324a5378d8db5/markdown.dtx#L22093-L22170
 [2]: https://daringfireball.net/projects/markdown/syntax#list
 [3]: https://spec.commonmark.org/0.30/#lists
