### ISSUE TITLE
List items may contain blockquotes

### ISSUE THREAD

**Issue by lostenderman** [lostenderman/markdown#75]
See <https://spec.commonmark.org/0.30/#example-320>

**Comment by Witiko** [comment]
The corresponding unit test is `testfiles/CommonMark_0.30/lists/020.test`:

``````````` md
%   ---RESULT--- "example": 320,
%   
%   <ul>
%   <li><em>a</em>
%   <blockquote>
%   <p><em>b</em></p>
%   </blockquote>
%   </li>
%   <li><em>c</em></li>
%   </ul>
%   
%   ---\RESULT---

<<<
* _a_
  > _b_
  >
* _c_
>>>
documentBegin
ulBeginTight
ulItem
emphasis: a
interblockSeparator
blockQuoteBegin
emphasis: b
blockQuoteEnd
ulItemEnd
ulItem
emphasis: c
ulItemEnd
ulEndTight
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/lists/020.test"`:

```````````
Testfile testfiles/CommonMark_0.30/lists/020.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command pdftex   --shell-escape                  --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-22 11:47:30.969759919 +0100
--- test-actual.log	2022-12-22 11:47:37.619701254 +0100
***************
*** 2,11 ****
  ulBeginTight
  ulItem
  emphasis: a
- interblockSeparator
- blockQuoteBegin
  emphasis: b
- blockQuoteEnd
  ulItemEnd
  ulItem
  emphasis: c
--- 2,8 ----
```````````

The issue seems related to [the PEG patterns for parsing lists][1] and blockquotes (([2][], [3][])), which handle indents in lists using the rules for Gruber's Markdown ([4][], [5][]) rather than CommonMark ([6][], [7][]).

 [1]: https://github.com/Witiko/markdown/blob/e9aa96e399ef59929c2c161f85d324a5378d8db5/markdown.dtx#L22093-L22170
 [2]: https://github.com/Witiko/markdown/blob/4bdde2988a54ad53346323ee3b5298b9e57d6633/markdown.dtx#L21792-L21813
 [3]: https://github.com/Witiko/markdown/blob/4bdde2988a54ad53346323ee3b5298b9e57d6633/markdown.dtx#L22070-L22072
 [4]: https://daringfireball.net/projects/markdown/syntax#list
 [5]: https://daringfireball.net/projects/markdown/syntax#blockquote
 [6]: https://spec.commonmark.org/0.30/#lists
 [7]: https://spec.commonmark.org/0.30/#block-quotes

**Comment by Witiko** [comment]
The corresponding unit test is `testfiles/CommonMark_0.30/lists/012.test`:

``````````` md
%   ---RESULT--- "example": 312,
%   
%   <ul>
%   <li><em>a</em></li>
%   <li><em>b</em></li>
%   <li><em>c</em></li>
%   <li><em>d</em>
%   - <em>e</em></li>
%   </ul>
%   
%   ---\RESULT---

<<<
- _a_
 - _b_
  - _c_
   - _d_
    - _e_
>>>
documentBegin
ulBeginTight
ulItem
emphasis: a
ulItemEnd
ulItem
emphasis: b
ulItemEnd
ulItem
emphasis: c
ulItemEnd
ulItem
emphasis: d
emphasis: e
ulItemEnd
ulEndTight
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/lists/012.test"`:

```````````
Testfile testfiles/CommonMark_0.30/lists/012.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command pdftex   --shell-escape                  --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-22 11:47:38.309695169 +0100
--- test-actual.log	2022-12-22 11:47:44.619639547 +0100
***************
*** 11,17 ****
--- 11,22 ----
  ulItemEnd
  ulItem
  emphasis: d
+ interblockSeparator
+ ulBeginTight
+ ulItem
  emphasis: e
  ulItemEnd
  ulEndTight
+ ulItemEnd
+ ulEndTight
  documentEnd
```````````

The issue seems related to [the PEG patterns for parsing lists][1], which handle indents in lists using the rules for [Gruber's Markdown][2] rather than [CommonMark][3].

 [1]: https://github.com/Witiko/markdown/blob/e9aa96e399ef59929c2c161f85d324a5378d8db5/markdown.dtx#L22093-L22170
 [2]: https://daringfireball.net/projects/markdown/syntax#list
 [3]: https://spec.commonmark.org/0.30/#lists
