### ISSUE TITLE
An HTML comment consists of <!-- + text + -->, where text does not start with > or ->, does not end with -, and does not contain --

### ISSUE THREAD

**Issue by lostenderman** [lostenderman/markdown#80]
See <https://spec.commonmark.org/0.30/#html-comment> and <https://spec.commonmark.org/0.30/#example-625>

**Comment by Witiko** [comment]
The corresponding unit test is `testfiles/CommonMark_0.30/raw_html/014.test`:

``````````` md
%   ---RESULT--- "example": 625,
%   
%   <p>foo &lt;!-- not a comment -- two hyphens --&gt;</p>
%   
%   ---\RESULT---

<<<
foo <!-- not a comment -- two hyphens -->
>>>
documentBegin
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/raw_html/014.test"`:

```````````
Testfile testfiles/CommonMark_0.30/raw_html/014.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command pdftex   --shell-escape                  --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-22 11:46:55.170076506 +0100
--- test-actual.log	2022-12-22 11:47:01.810017688 +0100
***************
*** 1,2 ****
--- 1,3 ----
  documentBegin
+ inlineHtmlComment: not a comment -- two hyphens
  documentEnd
```````````

The issue seems related to the PEG patterns for parsing HTML ([1][], [2][]), which use the rules for [Gruber's Markdown][3] rather than [CommonMark][4].

 [1]: https://github.com/Witiko/markdown/blob/4bdde2988a54ad53346323ee3b5298b9e57d6633/markdown.dtx#L21353-L21461
 [2]: https://github.com/Witiko/markdown/blob/4bdde2988a54ad53346323ee3b5298b9e57d6633/markdown.dtx#L22039-L22095
 [3]: https://daringfireball.net/projects/markdown/syntax#html
 [4]: https://spec.commonmark.org/0.30/#html-blocks
