### ISSUE TITLE
Processing instructions, declarations and CDATA sections should be recognised as valid tags

### ISSUE THREAD

**Issue by lostenderman** [lostenderman/markdown#81]
Processing instructions: <https://spec.commonmark.org/0.30/#processing-instruction> and <https://spec.commonmark.org/0.30/#example-627>

Declarations: <https://spec.commonmark.org/0.30/#declaration> and <https://spec.commonmark.org/0.30/#example-628>

CDATA sections: <https://spec.commonmark.org/0.30/#cdata-section> and <https://spec.commonmark.org/0.30/#example-629>

**Comment by Witiko** [comment]
The corresponding unit tests are:

- `testfiles/CommonMark_0.30/raw_html/016.test` (example 627)
- `testfiles/CommonMark_0.30/raw_html/017.test` (example 628)
- `testfiles/CommonMark_0.30/raw_html/018.test` (example 629)

For example 627, the issue seems to be with unit tests, which incorrectly assume that every element recognized by the parser must have an associated renderer. We [do recognize HTML instructions][5]; we just don't produce a renderer macro for them. Instead, we omit them in the TeX output.

For examples 628 and 629, the issue seems related to the PEG patterns for parsing HTML ([1][], [2][]), which use the rules for [Gruber's Markdown][3] rather than [CommonMark][4]. Specifically, our parser has no support for doctype declarations or CDATA sections.

For more details, see below.

 [1]: https://github.com/Witiko/markdown/blob/4bdde2988a54ad53346323ee3b5298b9e57d6633/markdown.dtx#L21353-L21461
 [2]: https://github.com/Witiko/markdown/blob/4bdde2988a54ad53346323ee3b5298b9e57d6633/markdown.dtx#L22039-L22095
 [3]: https://daringfireball.net/projects/markdown/syntax#html
 [4]: https://spec.commonmark.org/0.30/#html-blocks
 [5]: https://github.com/Witiko/markdown/blob/e9aa96e399ef59929c2c161f85d324a5378d8db5/markdown.dtx#L22044

# `testfiles/CommonMark_0.30/raw_html/016.test`

``````````` md
%   ---RESULT--- "example": 627,
%   
%   <p>foo <?php echo $a; ?></p>
%   
%   ---\RESULT---

<<<
foo <?php echo $a; ?>
>>>
documentBegin
inlineHtmlTag: <?php echo (dollarSign)a; ?>
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/raw_html/016.test"`:

```````````
Testfile testfiles/CommonMark_0.30/raw_html/016.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command pdftex   --shell-escape                  --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-22 14:27:56.584786548 +0100
--- test-actual.log	2022-12-22 14:28:04.024728941 +0100
***************
*** 1,3 ****
  documentBegin
- inlineHtmlTag: <?php echo (dollarSign)a; ?>
  documentEnd
--- 1,2 ----
```````````

# `testfiles/CommonMark_0.30/raw_html/017.test`

``````````` md
%   ---RESULT--- "example": 628,
%   
%   <p>foo <!ELEMENT br EMPTY></p>
%   
%   ---\RESULT---

<<<
foo <!ELEMENT br EMPTY>
>>>
documentBegin
inlineHtmlTag: <!ELEMENT br EMPTY>
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/raw_html/017.test"`:

```````````
Testfile testfiles/CommonMark_0.30/raw_html/017.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command pdftex   --shell-escape                  --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-22 14:28:20.694599858 +0100
--- test-actual.log	2022-12-22 14:28:27.494547199 +0100
***************
*** 1,3 ****
  documentBegin
- inlineHtmlTag: <!ELEMENT br EMPTY>
  documentEnd
--- 1,2 ----
```````````

# `testfiles/CommonMark_0.30/raw_html/018.test`

``````````` md
%   ---RESULT--- "example": 629,
%   
%   <p>foo <![CDATA[>&<]]></p>
%   
%   ---\RESULT---

<<<
foo <![CDATA[>&<]]>
>>>
documentBegin
inlineHtmlTag: <![CDATA[>(ampersand)<]]>
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/raw_html/018.test"`:

```````````
Testfile testfiles/CommonMark_0.30/raw_html/018.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command pdftex   --shell-escape                  --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-22 14:28:37.844467044 +0100
--- test-actual.log	2022-12-22 14:28:44.744413604 +0100
***************
*** 1,3 ****
  documentBegin
! inlineHtmlTag: <![CDATA[>(ampersand)<]]>
  documentEnd
--- 1,3 ----
  documentBegin
! ampersand
  documentEnd
```````````
