### ISSUE TITLE
Blockquote's optional space should not count as a content in an indented code block

### ISSUE THREAD

**Issue by lostenderman** [lostenderman/markdown#83]
See <https://spec.commonmark.org/0.30/#example-6>

**Comment by Witiko** [comment]
The corresponding unit test is `testfiles/CommonMark_0.30/tabs/006.test`:

``````````` md
%   ---RESULT--- "example": 6,
%   
%   <blockquote>
%   <pre><code>  foo
%   </code></pre>
%   </blockquote>
%   
%   ---\RESULT---

<<<
>		foo
>>>
documentBegin
blockQuoteBegin
inputVerbatim: ./_markdown_test/8f258c63c0e290338dc5f8d2f05855d3.verbatim
blockQuoteEnd
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/tabs/006.test"`:

```````````
Testfile testfiles/CommonMark_0.30/tabs/006.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command pdftex   --shell-escape                  --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-22 11:46:19.230395691 +0100
--- test-actual.log	2022-12-22 11:46:25.470340171 +0100
***************
*** 1,5 ****
  documentBegin
  blockQuoteBegin
! inputVerbatim: ./_markdown_test/8f258c63c0e290338dc5f8d2f05855d3.verbatim
  blockQuoteEnd
  documentEnd
--- 1,5 ----
  documentBegin
  blockQuoteBegin
! inputVerbatim: ./_markdown_test/c0fec4917765f9e66f1451923dfb05f2.verbatim
  blockQuoteEnd
  documentEnd
```````````

The issue seems related to the PEG patterns for blockquotes ([3][], [4][]), which use the rules for [Gruber's Markdown][6] rather than [CommonMark][8].

 [3]: https://github.com/Witiko/markdown/blob/4bdde2988a54ad53346323ee3b5298b9e57d6633/markdown.dtx#L21792-L21813
 [4]: https://github.com/Witiko/markdown/blob/4bdde2988a54ad53346323ee3b5298b9e57d6633/markdown.dtx#L22070-L22072
 [6]: https://daringfireball.net/projects/markdown/syntax#blockquote
 [8]: https://spec.commonmark.org/0.30/#block-quotes
