### ISSUE TITLE
A blank line is needed between a paragraph and a following setext heading

### ISSUE THREAD

**Issue by lostenderman** [lostenderman/markdown#88]
See <https://spec.commonmark.org/0.30/#example-95>

**Comment by Witiko** [comment]
The corresponding unit test is `testfiles/CommonMark_0.30/setext_headings/016.test`:

``````````` md
%   ---RESULT--- "example": 95,
%   
%   <h2>Foo
%   Bar</h2>
%   
%   ---\RESULT---

<<<
Foo
Bar
---
>>>
documentBegin
headingTwo: Foo Bar
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/setext_headings/016.test"`:

```````````
Testfile testfiles/CommonMark_0.30/setext_headings/016.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command pdftex   --shell-escape                  --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-22 11:45:42.710721525 +0100
--- test-actual.log	2022-12-22 11:45:49.360662076 +0100
***************
*** 1,3 ****
  documentBegin
! headingTwo: Foo Bar
  documentEnd
--- 1,4 ----
  documentBegin
! interblockSeparator
! headingTwo: Bar
  documentEnd
```````````

The issue seems related to the PEG patterns for parsing headings ([1][], [2][]), which use the rules for [Gruber's Markdown][3] rather than [CommonMark][4].

 [1]: https://github.com/Witiko/markdown/blob/4bdde2988a54ad53346323ee3b5298b9e57d6633/markdown.dtx#L21528-L21548
 [2]: https://github.com/Witiko/markdown/blob/4bdde2988a54ad53346323ee3b5298b9e57d6633/markdown.dtx#L22179-L22208
 [3]: https://daringfireball.net/projects/markdown/syntax#header
 [4]: https://spec.commonmark.org/0.30/#setext-headings
