### ISSUE TITLE
Setext heading text lines must not be interpretable as block constructs other than paragraphs

### ISSUE THREAD

**Issue by lostenderman** [lostenderman/markdown#89]
See <https://spec.commonmark.org/0.30/#example-98>

**Comment by Witiko** [comment]
The corresponding unit test is `testfiles/CommonMark_0.30/setext_headings/019.test`:

``````````` md
%   ---RESULT--- "example": 98,
%   
%   <hr />
%   <hr />
%   
%   ---\RESULT---

<<<
---
---
>>>
documentBegin
thematicBreak
interblockSeparator
thematicBreak
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/setext_headings/019.test"`:

```````````
Testfile testfiles/CommonMark_0.30/setext_headings/019.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command pdftex   --shell-escape                  --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-22 11:45:35.730783983 +0100
--- test-actual.log	2022-12-22 11:45:42.010727786 +0100
***************
*** 1,5 ****
  documentBegin
! thematicBreak
! interblockSeparator
! thematicBreak
  documentEnd
--- 1,3 ----
  documentBegin
! headingTwo: ---
  documentEnd
```````````

The issue seems related to the PEG patterns for parsing headings ([1][], [2][]), which use the rules for [Gruber's Markdown][3] rather than [CommonMark][4].

 [1]: https://github.com/Witiko/markdown/blob/4bdde2988a54ad53346323ee3b5298b9e57d6633/markdown.dtx#L21528-L21548
 [2]: https://github.com/Witiko/markdown/blob/4bdde2988a54ad53346323ee3b5298b9e57d6633/markdown.dtx#L22179-L22208
 [3]: https://daringfireball.net/projects/markdown/syntax#header
 [4]: https://spec.commonmark.org/0.30/#setext-headings
