### ISSUE TITLE
Strings that count as absolute URIs need not be valid URIs

### ISSUE THREAD

**Issue by lostenderman** [lostenderman/markdown#9]
See <https://spec.commonmark.org/0.30/#example-597>

**Comment by Witiko** [comment]
The corresponding unit test is `testfiles/CommonMark_0.30/autolinks/005.test`:

``````````` md
%   ---RESULT--- "example": 597,
%   
%   <p><a href="a+b+c:d">a+b+c:d</a></p>
%   
%   ---\RESULT---

<<<
<a+b+c:d>
>>>
documentBegin
BEGIN link
- label: a+b+c:d
- URI: a+b+c:d
- title: 
END link
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/autolinks/005.test"`:

```````````
Testfile testfiles/CommonMark_0.30/autolinks/005.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command pdftex   --shell-escape                  --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-22 12:00:27.783094206 +0100
--- test-actual.log	2022-12-22 12:00:34.593036788 +0100
***************
*** 1,7 ****
  documentBegin
- BEGIN link
- - label: a+b+c:d
- - URI: a+b+c:d
- - title: 
- END link
  documentEnd
--- 1,2 ----
```````````

The issue seems related to the PEG patterns for parsing [autolinks][1], which use the rules for [Gruber's Markdown][2] rather than [CommonMark][3].

 [1]: https://github.com/Witiko/markdown/blob/e9aa96e399ef59929c2c161f85d324a5378d8db5/markdown.dtx#L21983-L22005
 [2]: https://daringfireball.net/projects/markdown/syntax#autolink
 [3]: https://spec.commonmark.org/0.30/#autolinks
