### ISSUE TITLE
HTML blocks continue until they are closed by their appropriate end condition, or the last line of the document or other container block

### ISSUE THREAD

**Issue by lostenderman** [lostenderman/markdown#90]
See <https://spec.commonmark.org/0.30/#end-condition> and <https://spec.commonmark.org/0.30/#example-152>

**Comment by Witiko** [comment]
The corresponding unit test is `testfiles/CommonMark_0.30/html_blocks/005.test`:

``````````` md
%   ---RESULT--- "example": 152,
%   
%   <DIV CLASS="foo">
%   <p><em>Markdown</em></p>
%   </DIV>
%   
%   ---\RESULT---

<<<
<DIV CLASS="foo">

*Markdown*

</DIV>
>>>
documentBegin
inputBlockHtmlElement: ./_markdown_test/153f0f74866f457bd1531d964cc934a6.verbatim
interblockSeparator
emphasis: Markdown
interblockSeparator
inputBlockHtmlElement: ./_markdown_test/af0c41d3e6909eae31d92ec3cd4498a5.verbatim
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/html_blocks/005.test"`:

```````````
Testfile testfiles/CommonMark_0.30/html_blocks/005.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command pdftex   --shell-escape                  --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-22 11:45:28.550848292 +0100
--- test-actual.log	2022-12-22 11:45:35.070789891 +0100
***************
*** 1,7 ****
  documentBegin
! inputBlockHtmlElement: ./_markdown_test/153f0f74866f457bd1531d964cc934a6.verbatim
! interblockSeparator
! emphasis: Markdown
! interblockSeparator
! inputBlockHtmlElement: ./_markdown_test/af0c41d3e6909eae31d92ec3cd4498a5.verbatim
  documentEnd
--- 1,3 ----
  documentBegin
! inputBlockHtmlElement: ./_markdown_test/4ecfc84a43ece195756b3869a431e2a5.verbatim
  documentEnd
```````````

The issue seems related to the PEG patterns for parsing HTML blocks ([1][], [2][]), which handle indents in lists using the rules for [Gruber's Markdown][3] rather than [CommonMark][4].
For more details, see below.

 [1]: https://github.com/Witiko/markdown/blob/4bdde2988a54ad53346323ee3b5298b9e57d6633/markdown.dtx#L21353-L21461
 [2]: https://github.com/Witiko/markdown/blob/4bdde2988a54ad53346323ee3b5298b9e57d6633/markdown.dtx#L22039-L22095
 [3]: https://daringfireball.net/projects/markdown/syntax#html
 [4]: https://spec.commonmark.org/0.30/#html-blocks
