### ISSUE TITLE
The tag on the first line can be partial, as long as it is split where there would be whitespace

### ISSUE THREAD

**Issue by lostenderman** [lostenderman/markdown#92]
See <https://spec.commonmark.org/0.30/#example-154>

Follows #91

**Comment by Witiko** [comment]
The corresponding unit test is `testfiles/CommonMark_0.30/html_blocks/006.test`:

``````````` md
%   ---RESULT--- "example": 153,
%   
%   <div id="foo"
%     class="bar">
%   </div>
%   
%   ---\RESULT---

<<<
<div id="foo"
  class="bar">
</div>
>>>
documentBegin
inputBlockHtmlElement: ./_markdown_test/50364402fc2b6e3be554952f266f25ce.verbatim
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/html_blocks/006.test"`:

```````````
Testfile testfiles/CommonMark_0.30/html_blocks/006.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command pdftex   --shell-escape                  --interaction=nonstopmode  test.tex
      Command xetex    --shell-escape --8bit           --interaction=nonstopmode  test.tex
      Command luatex                                   --interaction=nonstopmode  test.tex
    Template templates/plain/verbatim.tex.m4
      Command pdftex   --shell-escape                  --interaction=nonstopmode  test.tex
      Command xetex    --shell-escape --8bit           --interaction=nonstopmode  test.tex
      Command luatex                                   --interaction=nonstopmode  test.tex
```````````

I cannot reproduce any issues.

**Comment by lostenderman** [comment]
The wrong example was referenced.

Example https://spec.commonmark.org/0.30/#example-154; however, does fail due to the reason specified above.

The description has been updated accordingly.

**Comment by Witiko** [comment]
The corresponding unit test is `testfiles/CommonMark_0.30/html_blocks/007.test`:

``````````` md
%   ---RESULT--- "example": 154,
%   
%   <div id="foo" class="bar
%     baz">
%   </div>
%   
%   ---\RESULT---

<<<
<div id="foo" class="bar
  baz">
</div>
>>>
documentBegin
inputBlockHtmlElement: ./_markdown_test/5958c7398ed8f6528d1252e17621e13e.verbatim
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/html_blocks/007.test"`:

```````````
Testfile testfiles/CommonMark_0.30/html_blocks/007.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command luatex                                   --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-29 21:47:14.831019443 +0100
--- test-actual.log	2022-12-29 21:47:21.770943624 +0100
***************
*** 1,3 ****
  documentBegin
! inputBlockHtmlElement: ./_markdown_test/5958c7398ed8f6528d1252e17621e13e.verbatim
  documentEnd
--- 1,3 ----
  documentBegin
! inlineHtmlTag: </div>
  documentEnd
```````````

The issue seems related to the PEG patterns for parsing HTML blocks ([1][], [2][]), which use the rules for [Gruber's Markdown][3] rather than [CommonMark][4].

 [1]: https://github.com/Witiko/markdown/blob/4bdde2988a54ad53346323ee3b5298b9e57d6633/markdown.dtx#L21353-L21461
 [2]: https://github.com/Witiko/markdown/blob/4bdde2988a54ad53346323ee3b5298b9e57d6633/markdown.dtx#L22039-L22095
 [3]: https://daringfireball.net/projects/markdown/syntax#html
 [4]: https://spec.commonmark.org/0.30/#html-blocks
