### ISSUE TITLE
Everything until the next blank line or end of document gets included in the HTML block

### ISSUE THREAD

**Issue by lostenderman** [lostenderman/markdown#95]
See <https://spec.commonmark.org/0.30/#example-161>

**Comment by Witiko** [comment]
The corresponding unit test is `testfiles/CommonMark_0.30/html_blocks/014.test`:

``````````` md
%   ---RESULT--- "example": 161,
%   
%   <div></div>
%   ``` c
%   int x = 33;
%   ```
%   
%   ---\RESULT---

<<<
<div></div>
``` c
int x = 33;
```
>>>
documentBegin
inputBlockHtmlElement: ./_markdown_test/9991376ef916f734b2c3ba85b9b2a248.verbatim
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/html_blocks/014.test"`:

```````````
Testfile testfiles/CommonMark_0.30/html_blocks/014.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command pdftex   --shell-escape                  --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-22 11:38:02.944758625 +0100
--- test-actual.log	2022-12-22 11:38:09.154708002 +0100
***************
*** 1,3 ****
  documentBegin
! inputBlockHtmlElement: ./_markdown_test/9991376ef916f734b2c3ba85b9b2a248.verbatim
  documentEnd
--- 1,8 ----
  documentBegin
! inputBlockHtmlElement: ./_markdown_test/f9df91370d9b344946e23cbcd6a1541f.verbatim
! interblockSeparator
! BEGIN fencedCode
! - src: ./_markdown_test/b10613e8161be18d807b8d8575a47966.verbatim
! - infostring: c
! END fencedCode
  documentEnd
```````````

The issue seems related to the PEG patterns for parsing HTML blocks ([1][], [2][]), which handle indents in lists using the rules for [Gruber's Markdown][3] rather than [CommonMark][4].

 [1]: https://github.com/Witiko/markdown/blob/4bdde2988a54ad53346323ee3b5298b9e57d6633/markdown.dtx#L21353-L21461
 [2]: https://github.com/Witiko/markdown/blob/4bdde2988a54ad53346323ee3b5298b9e57d6633/markdown.dtx#L22039-L22095
 [3]: https://daringfireball.net/projects/markdown/syntax#html
 [4]: https://spec.commonmark.org/0.30/#html-blocks
