### ISSUE TITLE
To start an HTML block with a tag that is not in the list of block-level tags, you must put the tag by itself on the first line (and it must be complete)

### ISSUE THREAD

**Issue by lostenderman** [lostenderman/markdown#96]
See <https://spec.commonmark.org/0.30/#example-162>

Follows #91

**Comment by Witiko** [comment]
The corresponding unit test is `testfiles/CommonMark_0.30/html_blocks/015.test`:

``````````` md
%   ---RESULT--- "example": 162,
%   
%   <a href="foo">
%   *bar*
%   </a>
%   
%   ---\RESULT---

<<<
<a href="foo">
*bar*
</a>
>>>
documentBegin
inputBlockHtmlElement: ./_markdown_test/80cb299274a91fd2edfed2bfe359aa0b.verbatim
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/html_blocks/015.test"`:

```````````
Testfile testfiles/CommonMark_0.30/html_blocks/015.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command pdftex   --shell-escape                  --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-22 11:38:54.724336518 +0100
--- test-actual.log	2022-12-22 11:39:00.954285731 +0100
***************
*** 1,3 ****
  documentBegin
! inputBlockHtmlElement: ./_markdown_test/80cb299274a91fd2edfed2bfe359aa0b.verbatim
  documentEnd
--- 1,5 ----
  documentBegin
! inlineHtmlTag: <a href="foo">
! emphasis: bar
! inlineHtmlTag: </a>
  documentEnd
```````````

The issue seems related to the PEG patterns for parsing HTML blocks ([1][], [2][]), which handle indents in lists using the rules for [Gruber's Markdown][3] rather than [CommonMark][4].

 [1]: https://github.com/Witiko/markdown/blob/4bdde2988a54ad53346323ee3b5298b9e57d6633/markdown.dtx#L21353-L21461
 [2]: https://github.com/Witiko/markdown/blob/4bdde2988a54ad53346323ee3b5298b9e57d6633/markdown.dtx#L22039-L22095
 [3]: https://daringfireball.net/projects/markdown/syntax#html
 [4]: https://spec.commonmark.org/0.30/#html-blocks
