### ISSUE TITLE
In type 7 blocks, the tag name can be anything

### ISSUE THREAD

**Issue by lostenderman** [lostenderman/markdown#97]
See <https://spec.commonmark.org/0.30/#example-163>

Follows #91

**Comment by Witiko** [comment]
The corresponding unit test is `testfiles/CommonMark_0.30/html_blocks/016.test`:

``````````` md
%   ---RESULT--- "example": 163,
%   
%   <Warning>
%   *bar*
%   </Warning>
%   
%   ---\RESULT---

<<<
<Warning>
*bar*
</Warning>
>>>
documentBegin
inputBlockHtmlElement: ./_markdown_test/0d75dd260dced5433ce33ba40fdaf904.verbatim
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/html_blocks/016.test"`:

```````````
Testfile testfiles/CommonMark_0.30/html_blocks/016.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command pdftex   --shell-escape                  --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-22 11:39:36.933992426 +0100
--- test-actual.log	2022-12-22 11:39:43.283940662 +0100
***************
*** 1,3 ****
  documentBegin
! inputBlockHtmlElement: ./_markdown_test/0d75dd260dced5433ce33ba40fdaf904.verbatim
  documentEnd
--- 1,5 ----
  documentBegin
! inlineHtmlTag: <Warning>
! emphasis: bar
! inlineHtmlTag: </Warning>
  documentEnd
```````````

The issue seems related to the PEG patterns for parsing HTML blocks ([1][], [2][]), which handle indents in lists using the rules for [Gruber's Markdown][3] rather than [CommonMark][4].

 [1]: https://github.com/Witiko/markdown/blob/4bdde2988a54ad53346323ee3b5298b9e57d6633/markdown.dtx#L21353-L21461
 [2]: https://github.com/Witiko/markdown/blob/4bdde2988a54ad53346323ee3b5298b9e57d6633/markdown.dtx#L22039-L22095
 [3]: https://daringfireball.net/projects/markdown/syntax#html
 [4]: https://spec.commonmark.org/0.30/#html-blocks
