### ISSUE TITLE
A following blank line is needed, except at the end of a document, and except for blocks of types 1–5

### ISSUE THREAD

**Issue by lostenderman** [lostenderman/markdown#98]
See <https://spec.commonmark.org/0.30/#example-186>

**Comment by Witiko** [comment]
The corresponding unit test is `testfiles/CommonMark_0.30/html_blocks/039.test`:

``````````` md
%   ---RESULT--- "example": 186,
%   
%   <div>
%   bar
%   </div>
%   *foo*
%   
%   ---\RESULT---

<<<
<div>
bar
</div>
*foo*
>>>
documentBegin
inputBlockHtmlElement: ./_markdown_test/7001f3dd24898bf2401acb6c9979b65d.verbatim
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/html_blocks/039.test"`:

```````````
Testfile testfiles/CommonMark_0.30/html_blocks/039.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command pdftex   --shell-escape                  --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-22 11:39:58.413817323 +0100
--- test-actual.log	2022-12-22 11:40:04.633766618 +0100
***************
*** 1,3 ****
  documentBegin
! inputBlockHtmlElement: ./_markdown_test/7001f3dd24898bf2401acb6c9979b65d.verbatim
  documentEnd
--- 1,5 ----
  documentBegin
! inputBlockHtmlElement: ./_markdown_test/c9dd120ae3847c13e8c50a74781845a9.verbatim
! interblockSeparator
! emphasis: foo
  documentEnd
```````````

The issue seems related to the PEG patterns for parsing HTML blocks ([1][], [2][]), which handle indents in lists using the rules for [Gruber's Markdown][3] rather than [CommonMark][4].

 [1]: https://github.com/Witiko/markdown/blob/4bdde2988a54ad53346323ee3b5298b9e57d6633/markdown.dtx#L21353-L21461
 [2]: https://github.com/Witiko/markdown/blob/4bdde2988a54ad53346323ee3b5298b9e57d6633/markdown.dtx#L22039-L22095
 [3]: https://daringfireball.net/projects/markdown/syntax#html
 [4]: https://spec.commonmark.org/0.30/#html-blocks
